/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AudioServer);
  }
}(this, function(expect, AudioServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AudioServer.SongUpdateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SongUpdateRequest', function() {
    it('should create an instance of SongUpdateRequest', function() {
      // uncomment below and update the code to test SongUpdateRequest
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be.a(AudioServer.SongUpdateRequest);
    });

    it('should have the property genre (base name: "genre")', function() {
      // uncomment below and update the code to test the property genre
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property artist (base name: "artist")', function() {
      // uncomment below and update the code to test the property artist
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property album (base name: "album")', function() {
      // uncomment below and update the code to test the property album
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property cover (base name: "cover")', function() {
      // uncomment below and update the code to test the property cover
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property release (base name: "release")', function() {
      // uncomment below and update the code to test the property release
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property trackno (base name: "trackno")', function() {
      // uncomment below and update the code to test the property trackno
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property metatags (base name: "metatags")', function() {
      // uncomment below and update the code to test the property metatags
      //var instance = new AudioServer.SongUpdateRequest();
      //expect(instance).to.be();
    });

  });

}));
