/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlbumCreateRequest,
  AlbumResponse,
  AlbumUpdateRequest,
  DeletedResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AlbumCreateRequestFromJSON,
    AlbumCreateRequestToJSON,
    AlbumResponseFromJSON,
    AlbumResponseToJSON,
    AlbumUpdateRequestFromJSON,
    AlbumUpdateRequestToJSON,
    DeletedResponseFromJSON,
    DeletedResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateAlbumApiV1AlbumPostRequest {
    albumCreateRequest: AlbumCreateRequest;
}

export interface DeleteAlbumApiV1AlbumIdDeleteRequest {
    id: number;
}

export interface GetAlbumApiV1AlbumIdGetRequest {
    id: number;
}

export interface GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest {
    id: number;
}

export interface GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest {
    id: number;
}

export interface GetGenresFromAlbumApiV1AlbumIdGenresGetRequest {
    id: number;
}

export interface GetSongsFromAlbumApiV1AlbumIdSongsGetRequest {
    id: number;
}

export interface UpdateAlbumApiV1AlbumIdPatchRequest {
    id: number;
    albumUpdateRequest: AlbumUpdateRequest;
}

/**
 * 
 */
export class AlbumApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAlbumApiV1AlbumPost without sending the request
     */
    async createAlbumApiV1AlbumPostRequestOpts(requestParameters: CreateAlbumApiV1AlbumPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['albumCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'albumCreateRequest',
                'Required parameter "albumCreateRequest" was null or undefined when calling createAlbumApiV1AlbumPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/album`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumCreateRequestToJSON(requestParameters['albumCreateRequest']),
        };
    }

    /**
     * Create Album
     */
    async createAlbumApiV1AlbumPostRaw(requestParameters: CreateAlbumApiV1AlbumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponse>> {
        const requestOptions = await this.createAlbumApiV1AlbumPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseFromJSON(jsonValue));
    }

    /**
     * Create Album
     */
    async createAlbumApiV1AlbumPost(requestParameters: CreateAlbumApiV1AlbumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponse> {
        const response = await this.createAlbumApiV1AlbumPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAlbumApiV1AlbumIdDelete without sending the request
     */
    async deleteAlbumApiV1AlbumIdDeleteRequestOpts(requestParameters: DeleteAlbumApiV1AlbumIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAlbumApiV1AlbumIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Album
     */
    async deleteAlbumApiV1AlbumIdDeleteRaw(requestParameters: DeleteAlbumApiV1AlbumIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteAlbumApiV1AlbumIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Album
     */
    async deleteAlbumApiV1AlbumIdDelete(requestParameters: DeleteAlbumApiV1AlbumIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteAlbumApiV1AlbumIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlbumApiV1AlbumIdGet without sending the request
     */
    async getAlbumApiV1AlbumIdGetRequestOpts(requestParameters: GetAlbumApiV1AlbumIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbumApiV1AlbumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Album
     */
    async getAlbumApiV1AlbumIdGetRaw(requestParameters: GetAlbumApiV1AlbumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponse>> {
        const requestOptions = await this.getAlbumApiV1AlbumIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseFromJSON(jsonValue));
    }

    /**
     * Get Album
     */
    async getAlbumApiV1AlbumIdGet(requestParameters: GetAlbumApiV1AlbumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponse> {
        const response = await this.getAlbumApiV1AlbumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet without sending the request
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequestOpts(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/albums`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Albums From Playlist
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRaw(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Albums From Playlist
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromAlbumApiV1AlbumIdFeaturesGet without sending the request
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromAlbumApiV1AlbumIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Album
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRaw(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Album
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenresFromAlbumApiV1AlbumIdGenresGet without sending the request
     */
    async getGenresFromAlbumApiV1AlbumIdGenresGetRequestOpts(requestParameters: GetGenresFromAlbumApiV1AlbumIdGenresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenresFromAlbumApiV1AlbumIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/genres`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genres From Album
     */
    async getGenresFromAlbumApiV1AlbumIdGenresGetRaw(requestParameters: GetGenresFromAlbumApiV1AlbumIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getGenresFromAlbumApiV1AlbumIdGenresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Genres From Album
     */
    async getGenresFromAlbumApiV1AlbumIdGenresGet(requestParameters: GetGenresFromAlbumApiV1AlbumIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGenresFromAlbumApiV1AlbumIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromAlbumApiV1AlbumIdSongsGet without sending the request
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGetRequestOpts(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromAlbumApiV1AlbumIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Album
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGetRaw(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromAlbumApiV1AlbumIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Album
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGet(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromAlbumApiV1AlbumIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllAlbumsApiV1AlbumsGet without sending the request
     */
    async listAllAlbumsApiV1AlbumsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/albums`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Albums
     */
    async listAllAlbumsApiV1AlbumsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlbumResponse>>> {
        const requestOptions = await this.listAllAlbumsApiV1AlbumsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumResponseFromJSON));
    }

    /**
     * List All Albums
     */
    async listAllAlbumsApiV1AlbumsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlbumResponse>> {
        const response = await this.listAllAlbumsApiV1AlbumsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAlbumApiV1AlbumIdPatch without sending the request
     */
    async updateAlbumApiV1AlbumIdPatchRequestOpts(requestParameters: UpdateAlbumApiV1AlbumIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAlbumApiV1AlbumIdPatch().'
            );
        }

        if (requestParameters['albumUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'albumUpdateRequest',
                'Required parameter "albumUpdateRequest" was null or undefined when calling updateAlbumApiV1AlbumIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/album/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumUpdateRequestToJSON(requestParameters['albumUpdateRequest']),
        };
    }

    /**
     * Update Album
     */
    async updateAlbumApiV1AlbumIdPatchRaw(requestParameters: UpdateAlbumApiV1AlbumIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponse>> {
        const requestOptions = await this.updateAlbumApiV1AlbumIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseFromJSON(jsonValue));
    }

    /**
     * Update Album
     */
    async updateAlbumApiV1AlbumIdPatch(requestParameters: UpdateAlbumApiV1AlbumIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponse> {
        const response = await this.updateAlbumApiV1AlbumIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
