/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArtistCreateRequest,
  ArtistResponse,
  ArtistUpdateRequest,
  DeletedResponse,
  HTTPValidationError,
} from '../models/index';
import {
    ArtistCreateRequestFromJSON,
    ArtistCreateRequestToJSON,
    ArtistResponseFromJSON,
    ArtistResponseToJSON,
    ArtistUpdateRequestFromJSON,
    ArtistUpdateRequestToJSON,
    DeletedResponseFromJSON,
    DeletedResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateArtistApiV1ArtistPostRequest {
    artistCreateRequest: ArtistCreateRequest;
}

export interface DeleteArtistApiV1ArtistIdDeleteRequest {
    id: number;
}

export interface GetArtistApiV1ArtistIdGetRequest {
    id: number;
}

export interface GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest {
    id: number;
}

export interface GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest {
    id: number;
}

export interface GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest {
    id: number;
}

export interface GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest {
    id: number;
}

export interface GetFeaturesFromSongApiV1SongIdFeaturesGetRequest {
    id: number;
}

export interface GetGenresFromArtistApiV1ArtistIdGenresGetRequest {
    id: number;
}

export interface GetSongsFromArtistApiV1ArtistIdSongsGetRequest {
    id: number;
}

export interface UpdateArtistApiV1ArtistIdPatchRequest {
    id: number;
    artistUpdateRequest: ArtistUpdateRequest;
}

/**
 * 
 */
export class ArtistApi extends runtime.BaseAPI {

    /**
     * Creates request options for createArtistApiV1ArtistPost without sending the request
     */
    async createArtistApiV1ArtistPostRequestOpts(requestParameters: CreateArtistApiV1ArtistPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'artistCreateRequest',
                'Required parameter "artistCreateRequest" was null or undefined when calling createArtistApiV1ArtistPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/artist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistCreateRequestToJSON(requestParameters['artistCreateRequest']),
        };
    }

    /**
     * Create Artist
     */
    async createArtistApiV1ArtistPostRaw(requestParameters: CreateArtistApiV1ArtistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistResponse>> {
        const requestOptions = await this.createArtistApiV1ArtistPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistResponseFromJSON(jsonValue));
    }

    /**
     * Create Artist
     */
    async createArtistApiV1ArtistPost(requestParameters: CreateArtistApiV1ArtistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistResponse> {
        const response = await this.createArtistApiV1ArtistPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteArtistApiV1ArtistIdDelete without sending the request
     */
    async deleteArtistApiV1ArtistIdDeleteRequestOpts(requestParameters: DeleteArtistApiV1ArtistIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteArtistApiV1ArtistIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Artist
     */
    async deleteArtistApiV1ArtistIdDeleteRaw(requestParameters: DeleteArtistApiV1ArtistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteArtistApiV1ArtistIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Artist
     */
    async deleteArtistApiV1ArtistIdDelete(requestParameters: DeleteArtistApiV1ArtistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteArtistApiV1ArtistIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getArtistApiV1ArtistIdGet without sending the request
     */
    async getArtistApiV1ArtistIdGetRequestOpts(requestParameters: GetArtistApiV1ArtistIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getArtistApiV1ArtistIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Artist
     */
    async getArtistApiV1ArtistIdGetRaw(requestParameters: GetArtistApiV1ArtistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistResponse>> {
        const requestOptions = await this.getArtistApiV1ArtistIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistResponseFromJSON(jsonValue));
    }

    /**
     * Get Artist
     */
    async getArtistApiV1ArtistIdGet(requestParameters: GetArtistApiV1ArtistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistResponse> {
        const response = await this.getArtistApiV1ArtistIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getArtistsFromPlaylistApiV1PlaylistIdArtistsGet without sending the request
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequestOpts(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getArtistsFromPlaylistApiV1PlaylistIdArtistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/artists`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Artists From Playlist
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRaw(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Artists From Playlist
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGet(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet without sending the request
     */
    async getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequestOpts(requestParameters: GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/collaborations`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Collaborations From Artist
     */
    async getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRaw(requestParameters: GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Collaborations From Artist
     */
    async getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet(requestParameters: GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromAlbumApiV1AlbumIdFeaturesGet without sending the request
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromAlbumApiV1AlbumIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Album
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRaw(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Album
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromArtistApiV1ArtistIdFeaturesGet without sending the request
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromArtistApiV1ArtistIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Artist
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGetRaw(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromArtistApiV1ArtistIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Artist
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGet(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromArtistApiV1ArtistIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromSongApiV1SongIdFeaturesGet without sending the request
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromSongApiV1SongIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Song
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGetRaw(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromSongApiV1SongIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Song
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGet(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromSongApiV1SongIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenresFromArtistApiV1ArtistIdGenresGet without sending the request
     */
    async getGenresFromArtistApiV1ArtistIdGenresGetRequestOpts(requestParameters: GetGenresFromArtistApiV1ArtistIdGenresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenresFromArtistApiV1ArtistIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/genres`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genres From Artist
     */
    async getGenresFromArtistApiV1ArtistIdGenresGetRaw(requestParameters: GetGenresFromArtistApiV1ArtistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getGenresFromArtistApiV1ArtistIdGenresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Genres From Artist
     */
    async getGenresFromArtistApiV1ArtistIdGenresGet(requestParameters: GetGenresFromArtistApiV1ArtistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGenresFromArtistApiV1ArtistIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromArtistApiV1ArtistIdSongsGet without sending the request
     */
    async getSongsFromArtistApiV1ArtistIdSongsGetRequestOpts(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromArtistApiV1ArtistIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Artist
     */
    async getSongsFromArtistApiV1ArtistIdSongsGetRaw(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromArtistApiV1ArtistIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Artist
     */
    async getSongsFromArtistApiV1ArtistIdSongsGet(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromArtistApiV1ArtistIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllArtistApiV1ArtistsGet without sending the request
     */
    async listAllArtistApiV1ArtistsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Artist
     */
    async listAllArtistApiV1ArtistsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ArtistResponse>>> {
        const requestOptions = await this.listAllArtistApiV1ArtistsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ArtistResponseFromJSON));
    }

    /**
     * List All Artist
     */
    async listAllArtistApiV1ArtistsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ArtistResponse>> {
        const response = await this.listAllArtistApiV1ArtistsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateArtistApiV1ArtistIdPatch without sending the request
     */
    async updateArtistApiV1ArtistIdPatchRequestOpts(requestParameters: UpdateArtistApiV1ArtistIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateArtistApiV1ArtistIdPatch().'
            );
        }

        if (requestParameters['artistUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'artistUpdateRequest',
                'Required parameter "artistUpdateRequest" was null or undefined when calling updateArtistApiV1ArtistIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/artist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistUpdateRequestToJSON(requestParameters['artistUpdateRequest']),
        };
    }

    /**
     * Update Artist
     */
    async updateArtistApiV1ArtistIdPatchRaw(requestParameters: UpdateArtistApiV1ArtistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistResponse>> {
        const requestOptions = await this.updateArtistApiV1ArtistIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistResponseFromJSON(jsonValue));
    }

    /**
     * Update Artist
     */
    async updateArtistApiV1ArtistIdPatch(requestParameters: UpdateArtistApiV1ArtistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistResponse> {
        const response = await this.updateArtistApiV1ArtistIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
