/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface SetDatabaseApiV1DbPatchRequest {
    path: string;
}

/**
 * 
 */
export class DatabaseApi extends runtime.BaseAPI {

    /**
     * Creates request options for setDatabaseApiV1DbPatch without sending the request
     */
    async setDatabaseApiV1DbPatchRequestOpts(requestParameters: SetDatabaseApiV1DbPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling setDatabaseApiV1DbPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/db`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Set Database
     */
    async setDatabaseApiV1DbPatchRaw(requestParameters: SetDatabaseApiV1DbPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const requestOptions = await this.setDatabaseApiV1DbPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Set Database
     */
    async setDatabaseApiV1DbPatch(requestParameters: SetDatabaseApiV1DbPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.setDatabaseApiV1DbPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
