/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeletedResponse,
  HTTPValidationError,
  PlaylistCreateRequest,
  PlaylistResponse,
  PlaylistUpdateRequest,
} from '../models/index';
import {
    DeletedResponseFromJSON,
    DeletedResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PlaylistCreateRequestFromJSON,
    PlaylistCreateRequestToJSON,
    PlaylistResponseFromJSON,
    PlaylistResponseToJSON,
    PlaylistUpdateRequestFromJSON,
    PlaylistUpdateRequestToJSON,
} from '../models/index';

export interface CreatePlaylistApiV1PlaylistPostRequest {
    playlistCreateRequest: PlaylistCreateRequest;
}

export interface DeletePlaylistApiV1PlaylistIdDeleteRequest {
    id: number;
}

export interface GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest {
    id: number;
}

export interface GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest {
    id: number;
}

export interface GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest {
    id: number;
}

export interface GetPlaylistApiV1PlaylistIdGetRequest {
    id: number;
}

export interface GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest {
    id: number;
}

export interface GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest {
    id: number;
}

export interface UpdatePlaylistApiV1PlaylistIdPatchRequest {
    id: number;
    playlistUpdateRequest: PlaylistUpdateRequest;
}

/**
 * 
 */
export class PlaylistApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPlaylistApiV1PlaylistPost without sending the request
     */
    async createPlaylistApiV1PlaylistPostRequestOpts(requestParameters: CreatePlaylistApiV1PlaylistPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playlistCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'playlistCreateRequest',
                'Required parameter "playlistCreateRequest" was null or undefined when calling createPlaylistApiV1PlaylistPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/playlist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaylistCreateRequestToJSON(requestParameters['playlistCreateRequest']),
        };
    }

    /**
     * Create Playlist
     */
    async createPlaylistApiV1PlaylistPostRaw(requestParameters: CreatePlaylistApiV1PlaylistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistResponse>> {
        const requestOptions = await this.createPlaylistApiV1PlaylistPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistResponseFromJSON(jsonValue));
    }

    /**
     * Create Playlist
     */
    async createPlaylistApiV1PlaylistPost(requestParameters: CreatePlaylistApiV1PlaylistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistResponse> {
        const response = await this.createPlaylistApiV1PlaylistPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePlaylistApiV1PlaylistIdDelete without sending the request
     */
    async deletePlaylistApiV1PlaylistIdDeleteRequestOpts(requestParameters: DeletePlaylistApiV1PlaylistIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePlaylistApiV1PlaylistIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Playlist
     */
    async deletePlaylistApiV1PlaylistIdDeleteRaw(requestParameters: DeletePlaylistApiV1PlaylistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deletePlaylistApiV1PlaylistIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Playlist
     */
    async deletePlaylistApiV1PlaylistIdDelete(requestParameters: DeletePlaylistApiV1PlaylistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deletePlaylistApiV1PlaylistIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet without sending the request
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequestOpts(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/albums`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Albums From Playlist
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRaw(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Albums From Playlist
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getArtistsFromPlaylistApiV1PlaylistIdArtistsGet without sending the request
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequestOpts(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getArtistsFromPlaylistApiV1PlaylistIdArtistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/artists`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Artists From Playlist
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRaw(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Artists From Playlist
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGet(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenresFromPlaylistApiV1PlaylistIdGenresGet without sending the request
     */
    async getGenresFromPlaylistApiV1PlaylistIdGenresGetRequestOpts(requestParameters: GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenresFromPlaylistApiV1PlaylistIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/genres`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genres From Playlist
     */
    async getGenresFromPlaylistApiV1PlaylistIdGenresGetRaw(requestParameters: GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getGenresFromPlaylistApiV1PlaylistIdGenresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Genres From Playlist
     */
    async getGenresFromPlaylistApiV1PlaylistIdGenresGet(requestParameters: GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGenresFromPlaylistApiV1PlaylistIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlaylistApiV1PlaylistIdGet without sending the request
     */
    async getPlaylistApiV1PlaylistIdGetRequestOpts(requestParameters: GetPlaylistApiV1PlaylistIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlaylistApiV1PlaylistIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Playlist
     */
    async getPlaylistApiV1PlaylistIdGetRaw(requestParameters: GetPlaylistApiV1PlaylistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistResponse>> {
        const requestOptions = await this.getPlaylistApiV1PlaylistIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistResponseFromJSON(jsonValue));
    }

    /**
     * Get Playlist
     */
    async getPlaylistApiV1PlaylistIdGet(requestParameters: GetPlaylistApiV1PlaylistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistResponse> {
        const response = await this.getPlaylistApiV1PlaylistIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet without sending the request
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequestOpts(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/playlists`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Playlists Song Is Part Of
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRaw(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Playlists Song Is Part Of
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromPlaylistApiV1PlaylistIdSongsGet without sending the request
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGetRequestOpts(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromPlaylistApiV1PlaylistIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Playlist
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGetRaw(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromPlaylistApiV1PlaylistIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Playlist
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGet(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromPlaylistApiV1PlaylistIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllPlaylistsApiV1PlaylistsGet without sending the request
     */
    async listAllPlaylistsApiV1PlaylistsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Playlists
     */
    async listAllPlaylistsApiV1PlaylistsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistResponse>>> {
        const requestOptions = await this.listAllPlaylistsApiV1PlaylistsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistResponseFromJSON));
    }

    /**
     * List All Playlists
     */
    async listAllPlaylistsApiV1PlaylistsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistResponse>> {
        const response = await this.listAllPlaylistsApiV1PlaylistsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePlaylistApiV1PlaylistIdPatch without sending the request
     */
    async updatePlaylistApiV1PlaylistIdPatchRequestOpts(requestParameters: UpdatePlaylistApiV1PlaylistIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePlaylistApiV1PlaylistIdPatch().'
            );
        }

        if (requestParameters['playlistUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'playlistUpdateRequest',
                'Required parameter "playlistUpdateRequest" was null or undefined when calling updatePlaylistApiV1PlaylistIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/playlist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PlaylistUpdateRequestToJSON(requestParameters['playlistUpdateRequest']),
        };
    }

    /**
     * Update Playlist
     */
    async updatePlaylistApiV1PlaylistIdPatchRaw(requestParameters: UpdatePlaylistApiV1PlaylistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistResponse>> {
        const requestOptions = await this.updatePlaylistApiV1PlaylistIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistResponseFromJSON(jsonValue));
    }

    /**
     * Update Playlist
     */
    async updatePlaylistApiV1PlaylistIdPatch(requestParameters: UpdatePlaylistApiV1PlaylistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistResponse> {
        const response = await this.updatePlaylistApiV1PlaylistIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
