/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeletedResponse,
  HTTPValidationError,
  SongResponse,
  SongUpdateRequest,
} from '../models/index';
import {
    DeletedResponseFromJSON,
    DeletedResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SongResponseFromJSON,
    SongResponseToJSON,
    SongUpdateRequestFromJSON,
    SongUpdateRequestToJSON,
} from '../models/index';

export interface DeleteSongApiV1SongIdDeleteRequest {
    id: number;
}

export interface GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest {
    id: number;
}

export interface GetFeaturesFromSongApiV1SongIdFeaturesGetRequest {
    id: number;
}

export interface GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest {
    id: number;
}

export interface GetSongApiV1SongIdGetRequest {
    id: number;
}

export interface GetSongsFromAlbumApiV1AlbumIdSongsGetRequest {
    id: number;
}

export interface GetSongsFromArtistApiV1ArtistIdSongsGetRequest {
    id: number;
}

export interface GetSongsFromGenreApiV1GenreIdSongsGetRequest {
    id: number;
}

export interface GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest {
    id: number;
}

export interface StreamSongApiV1SongIdStreamGetRequest {
    id: number;
}

export interface UpdateSongApiV1SongIdPatchRequest {
    id: number;
    songUpdateRequest: SongUpdateRequest;
}

export interface UploadSongApiV1SongPostRequest {
    file: string;
}

/**
 * 
 */
export class SongApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteSongApiV1SongIdDelete without sending the request
     */
    async deleteSongApiV1SongIdDeleteRequestOpts(requestParameters: DeleteSongApiV1SongIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSongApiV1SongIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Song
     */
    async deleteSongApiV1SongIdDeleteRaw(requestParameters: DeleteSongApiV1SongIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteSongApiV1SongIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Song
     */
    async deleteSongApiV1SongIdDelete(requestParameters: DeleteSongApiV1SongIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteSongApiV1SongIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromArtistApiV1ArtistIdFeaturesGet without sending the request
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromArtistApiV1ArtistIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Artist
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGetRaw(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromArtistApiV1ArtistIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Artist
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGet(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromArtistApiV1ArtistIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromSongApiV1SongIdFeaturesGet without sending the request
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromSongApiV1SongIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Song
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGetRaw(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromSongApiV1SongIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Song
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGet(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromSongApiV1SongIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet without sending the request
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequestOpts(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/playlists`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Playlists Song Is Part Of
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRaw(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Playlists Song Is Part Of
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongApiV1SongIdGet without sending the request
     */
    async getSongApiV1SongIdGetRequestOpts(requestParameters: GetSongApiV1SongIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongApiV1SongIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Song
     */
    async getSongApiV1SongIdGetRaw(requestParameters: GetSongApiV1SongIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SongResponse>> {
        const requestOptions = await this.getSongApiV1SongIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongResponseFromJSON(jsonValue));
    }

    /**
     * Get Song
     */
    async getSongApiV1SongIdGet(requestParameters: GetSongApiV1SongIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SongResponse> {
        const response = await this.getSongApiV1SongIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromAlbumApiV1AlbumIdSongsGet without sending the request
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGetRequestOpts(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromAlbumApiV1AlbumIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Album
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGetRaw(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromAlbumApiV1AlbumIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Album
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGet(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromAlbumApiV1AlbumIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromArtistApiV1ArtistIdSongsGet without sending the request
     */
    async getSongsFromArtistApiV1ArtistIdSongsGetRequestOpts(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromArtistApiV1ArtistIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Artist
     */
    async getSongsFromArtistApiV1ArtistIdSongsGetRaw(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromArtistApiV1ArtistIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Artist
     */
    async getSongsFromArtistApiV1ArtistIdSongsGet(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromArtistApiV1ArtistIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromGenreApiV1GenreIdSongsGet without sending the request
     */
    async getSongsFromGenreApiV1GenreIdSongsGetRequestOpts(requestParameters: GetSongsFromGenreApiV1GenreIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromGenreApiV1GenreIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genre/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Genre
     */
    async getSongsFromGenreApiV1GenreIdSongsGetRaw(requestParameters: GetSongsFromGenreApiV1GenreIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromGenreApiV1GenreIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Genre
     */
    async getSongsFromGenreApiV1GenreIdSongsGet(requestParameters: GetSongsFromGenreApiV1GenreIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromGenreApiV1GenreIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromPlaylistApiV1PlaylistIdSongsGet without sending the request
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGetRequestOpts(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromPlaylistApiV1PlaylistIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Playlist
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGetRaw(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromPlaylistApiV1PlaylistIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Playlist
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGet(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromPlaylistApiV1PlaylistIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllSongApiV1SongsGet without sending the request
     */
    async listAllSongApiV1SongsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/songs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Song
     */
    async listAllSongApiV1SongsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SongResponse>>> {
        const requestOptions = await this.listAllSongApiV1SongsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SongResponseFromJSON));
    }

    /**
     * List All Song
     */
    async listAllSongApiV1SongsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SongResponse>> {
        const response = await this.listAllSongApiV1SongsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamSongApiV1SongIdStreamGet without sending the request
     */
    async streamSongApiV1SongIdStreamGetRequestOpts(requestParameters: StreamSongApiV1SongIdStreamGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling streamSongApiV1SongIdStreamGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/stream`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stream Song
     */
    async streamSongApiV1SongIdStreamGetRaw(requestParameters: StreamSongApiV1SongIdStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.streamSongApiV1SongIdStreamGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stream Song
     */
    async streamSongApiV1SongIdStreamGet(requestParameters: StreamSongApiV1SongIdStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.streamSongApiV1SongIdStreamGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateSongApiV1SongIdPatch without sending the request
     */
    async updateSongApiV1SongIdPatchRequestOpts(requestParameters: UpdateSongApiV1SongIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSongApiV1SongIdPatch().'
            );
        }

        if (requestParameters['songUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'songUpdateRequest',
                'Required parameter "songUpdateRequest" was null or undefined when calling updateSongApiV1SongIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/song/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SongUpdateRequestToJSON(requestParameters['songUpdateRequest']),
        };
    }

    /**
     * Update Song
     */
    async updateSongApiV1SongIdPatchRaw(requestParameters: UpdateSongApiV1SongIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SongResponse>> {
        const requestOptions = await this.updateSongApiV1SongIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongResponseFromJSON(jsonValue));
    }

    /**
     * Update Song
     */
    async updateSongApiV1SongIdPatch(requestParameters: UpdateSongApiV1SongIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SongResponse> {
        const response = await this.updateSongApiV1SongIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadSongApiV1SongPost without sending the request
     */
    async uploadSongApiV1SongPostRequestOpts(requestParameters: UploadSongApiV1SongPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadSongApiV1SongPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/v1/song`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload Song
     */
    async uploadSongApiV1SongPostRaw(requestParameters: UploadSongApiV1SongPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SongResponse>> {
        const requestOptions = await this.uploadSongApiV1SongPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongResponseFromJSON(jsonValue));
    }

    /**
     * Upload Song
     */
    async uploadSongApiV1SongPost(requestParameters: UploadSongApiV1SongPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SongResponse> {
        const response = await this.uploadSongApiV1SongPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
