/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlbumCreateRequest,
  AlbumResponse,
  AlbumUpdateRequest,
  ArtistCreateRequest,
  ArtistResponse,
  ArtistUpdateRequest,
  DeletedResponse,
  GenreCreateRequest,
  GenreResponse,
  GenreUpdateRequest,
  HTTPValidationError,
  PlaylistCreateRequest,
  PlaylistResponse,
  PlaylistUpdateRequest,
  SongResponse,
  SongUpdateRequest,
} from '../models/index';
import {
    AlbumCreateRequestFromJSON,
    AlbumCreateRequestToJSON,
    AlbumResponseFromJSON,
    AlbumResponseToJSON,
    AlbumUpdateRequestFromJSON,
    AlbumUpdateRequestToJSON,
    ArtistCreateRequestFromJSON,
    ArtistCreateRequestToJSON,
    ArtistResponseFromJSON,
    ArtistResponseToJSON,
    ArtistUpdateRequestFromJSON,
    ArtistUpdateRequestToJSON,
    DeletedResponseFromJSON,
    DeletedResponseToJSON,
    GenreCreateRequestFromJSON,
    GenreCreateRequestToJSON,
    GenreResponseFromJSON,
    GenreResponseToJSON,
    GenreUpdateRequestFromJSON,
    GenreUpdateRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PlaylistCreateRequestFromJSON,
    PlaylistCreateRequestToJSON,
    PlaylistResponseFromJSON,
    PlaylistResponseToJSON,
    PlaylistUpdateRequestFromJSON,
    PlaylistUpdateRequestToJSON,
    SongResponseFromJSON,
    SongResponseToJSON,
    SongUpdateRequestFromJSON,
    SongUpdateRequestToJSON,
} from '../models/index';

export interface AddImageApiV1ImagePostRequest {
    file: string;
}

export interface CreateAlbumApiV1AlbumPostRequest {
    albumCreateRequest: AlbumCreateRequest;
}

export interface CreateArtistApiV1ArtistPostRequest {
    artistCreateRequest: ArtistCreateRequest;
}

export interface CreateGenreApiV1GenrePostRequest {
    genreCreateRequest: GenreCreateRequest;
}

export interface CreatePlaylistApiV1PlaylistPostRequest {
    playlistCreateRequest: PlaylistCreateRequest;
}

export interface DeleteAlbumApiV1AlbumIdDeleteRequest {
    id: number;
}

export interface DeleteArtistApiV1ArtistIdDeleteRequest {
    id: number;
}

export interface DeleteGenreApiV1GenreIdDeleteRequest {
    id: number;
}

export interface DeleteImageApiV1ImageIdDeleteRequest {
    id: number;
}

export interface DeletePlaylistApiV1PlaylistIdDeleteRequest {
    id: number;
}

export interface DeleteSongApiV1SongIdDeleteRequest {
    id: number;
}

export interface GetAlbumApiV1AlbumIdGetRequest {
    id: number;
}

export interface GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest {
    id: number;
}

export interface GetArtistApiV1ArtistIdGetRequest {
    id: number;
}

export interface GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest {
    id: number;
}

export interface GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest {
    id: number;
}

export interface GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest {
    id: number;
}

export interface GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest {
    id: number;
}

export interface GetFeaturesFromSongApiV1SongIdFeaturesGetRequest {
    id: number;
}

export interface GetGenreApiV1GenreIdGetRequest {
    id: number;
}

export interface GetGenresFromAlbumApiV1AlbumIdGenresGetRequest {
    id: number;
}

export interface GetGenresFromArtistApiV1ArtistIdGenresGetRequest {
    id: number;
}

export interface GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest {
    id: number;
}

export interface GetImageApiV1ImageIdGetRequest {
    id: number;
}

export interface GetPlaylistApiV1PlaylistIdGetRequest {
    id: number;
}

export interface GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest {
    id: number;
}

export interface GetSongApiV1SongIdGetRequest {
    id: number;
}

export interface GetSongsFromAlbumApiV1AlbumIdSongsGetRequest {
    id: number;
}

export interface GetSongsFromArtistApiV1ArtistIdSongsGetRequest {
    id: number;
}

export interface GetSongsFromGenreApiV1GenreIdSongsGetRequest {
    id: number;
}

export interface GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest {
    id: number;
}

export interface SetDatabaseApiV1DbPatchRequest {
    path: string;
}

export interface StreamSongApiV1SongIdStreamGetRequest {
    id: number;
}

export interface UpdateAlbumApiV1AlbumIdPatchRequest {
    id: number;
    albumUpdateRequest: AlbumUpdateRequest;
}

export interface UpdateArtistApiV1ArtistIdPatchRequest {
    id: number;
    artistUpdateRequest: ArtistUpdateRequest;
}

export interface UpdateGenreApiV1GenreIdPatchRequest {
    id: number;
    genreUpdateRequest: GenreUpdateRequest;
}

export interface UpdatePlaylistApiV1PlaylistIdPatchRequest {
    id: number;
    playlistUpdateRequest: PlaylistUpdateRequest;
}

export interface UpdateSongApiV1SongIdPatchRequest {
    id: number;
    songUpdateRequest: SongUpdateRequest;
}

export interface UploadSongApiV1SongPostRequest {
    file: string;
}

/**
 * 
 */
export class V1Api extends runtime.BaseAPI {

    /**
     * Creates request options for addImageApiV1ImagePost without sending the request
     */
    async addImageApiV1ImagePostRequestOpts(requestParameters: AddImageApiV1ImagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling addImageApiV1ImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/v1/image`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Add Image
     */
    async addImageApiV1ImagePostRaw(requestParameters: AddImageApiV1ImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.addImageApiV1ImagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Image
     */
    async addImageApiV1ImagePost(requestParameters: AddImageApiV1ImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.addImageApiV1ImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAlbumApiV1AlbumPost without sending the request
     */
    async createAlbumApiV1AlbumPostRequestOpts(requestParameters: CreateAlbumApiV1AlbumPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['albumCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'albumCreateRequest',
                'Required parameter "albumCreateRequest" was null or undefined when calling createAlbumApiV1AlbumPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/album`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumCreateRequestToJSON(requestParameters['albumCreateRequest']),
        };
    }

    /**
     * Create Album
     */
    async createAlbumApiV1AlbumPostRaw(requestParameters: CreateAlbumApiV1AlbumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponse>> {
        const requestOptions = await this.createAlbumApiV1AlbumPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseFromJSON(jsonValue));
    }

    /**
     * Create Album
     */
    async createAlbumApiV1AlbumPost(requestParameters: CreateAlbumApiV1AlbumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponse> {
        const response = await this.createAlbumApiV1AlbumPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createArtistApiV1ArtistPost without sending the request
     */
    async createArtistApiV1ArtistPostRequestOpts(requestParameters: CreateArtistApiV1ArtistPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'artistCreateRequest',
                'Required parameter "artistCreateRequest" was null or undefined when calling createArtistApiV1ArtistPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/artist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistCreateRequestToJSON(requestParameters['artistCreateRequest']),
        };
    }

    /**
     * Create Artist
     */
    async createArtistApiV1ArtistPostRaw(requestParameters: CreateArtistApiV1ArtistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistResponse>> {
        const requestOptions = await this.createArtistApiV1ArtistPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistResponseFromJSON(jsonValue));
    }

    /**
     * Create Artist
     */
    async createArtistApiV1ArtistPost(requestParameters: CreateArtistApiV1ArtistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistResponse> {
        const response = await this.createArtistApiV1ArtistPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createGenreApiV1GenrePost without sending the request
     */
    async createGenreApiV1GenrePostRequestOpts(requestParameters: CreateGenreApiV1GenrePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['genreCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'genreCreateRequest',
                'Required parameter "genreCreateRequest" was null or undefined when calling createGenreApiV1GenrePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/genre`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenreCreateRequestToJSON(requestParameters['genreCreateRequest']),
        };
    }

    /**
     * Create Genre
     */
    async createGenreApiV1GenrePostRaw(requestParameters: CreateGenreApiV1GenrePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenreResponse>> {
        const requestOptions = await this.createGenreApiV1GenrePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenreResponseFromJSON(jsonValue));
    }

    /**
     * Create Genre
     */
    async createGenreApiV1GenrePost(requestParameters: CreateGenreApiV1GenrePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenreResponse> {
        const response = await this.createGenreApiV1GenrePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPlaylistApiV1PlaylistPost without sending the request
     */
    async createPlaylistApiV1PlaylistPostRequestOpts(requestParameters: CreatePlaylistApiV1PlaylistPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playlistCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'playlistCreateRequest',
                'Required parameter "playlistCreateRequest" was null or undefined when calling createPlaylistApiV1PlaylistPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/playlist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaylistCreateRequestToJSON(requestParameters['playlistCreateRequest']),
        };
    }

    /**
     * Create Playlist
     */
    async createPlaylistApiV1PlaylistPostRaw(requestParameters: CreatePlaylistApiV1PlaylistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistResponse>> {
        const requestOptions = await this.createPlaylistApiV1PlaylistPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistResponseFromJSON(jsonValue));
    }

    /**
     * Create Playlist
     */
    async createPlaylistApiV1PlaylistPost(requestParameters: CreatePlaylistApiV1PlaylistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistResponse> {
        const response = await this.createPlaylistApiV1PlaylistPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAlbumApiV1AlbumIdDelete without sending the request
     */
    async deleteAlbumApiV1AlbumIdDeleteRequestOpts(requestParameters: DeleteAlbumApiV1AlbumIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAlbumApiV1AlbumIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Album
     */
    async deleteAlbumApiV1AlbumIdDeleteRaw(requestParameters: DeleteAlbumApiV1AlbumIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteAlbumApiV1AlbumIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Album
     */
    async deleteAlbumApiV1AlbumIdDelete(requestParameters: DeleteAlbumApiV1AlbumIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteAlbumApiV1AlbumIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteArtistApiV1ArtistIdDelete without sending the request
     */
    async deleteArtistApiV1ArtistIdDeleteRequestOpts(requestParameters: DeleteArtistApiV1ArtistIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteArtistApiV1ArtistIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Artist
     */
    async deleteArtistApiV1ArtistIdDeleteRaw(requestParameters: DeleteArtistApiV1ArtistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteArtistApiV1ArtistIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Artist
     */
    async deleteArtistApiV1ArtistIdDelete(requestParameters: DeleteArtistApiV1ArtistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteArtistApiV1ArtistIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteGenreApiV1GenreIdDelete without sending the request
     */
    async deleteGenreApiV1GenreIdDeleteRequestOpts(requestParameters: DeleteGenreApiV1GenreIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteGenreApiV1GenreIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genre/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Genre
     */
    async deleteGenreApiV1GenreIdDeleteRaw(requestParameters: DeleteGenreApiV1GenreIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteGenreApiV1GenreIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Genre
     */
    async deleteGenreApiV1GenreIdDelete(requestParameters: DeleteGenreApiV1GenreIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteGenreApiV1GenreIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteImageApiV1ImageIdDelete without sending the request
     */
    async deleteImageApiV1ImageIdDeleteRequestOpts(requestParameters: DeleteImageApiV1ImageIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteImageApiV1ImageIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/image/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Image
     */
    async deleteImageApiV1ImageIdDeleteRaw(requestParameters: DeleteImageApiV1ImageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteImageApiV1ImageIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Image
     */
    async deleteImageApiV1ImageIdDelete(requestParameters: DeleteImageApiV1ImageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteImageApiV1ImageIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePlaylistApiV1PlaylistIdDelete without sending the request
     */
    async deletePlaylistApiV1PlaylistIdDeleteRequestOpts(requestParameters: DeletePlaylistApiV1PlaylistIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePlaylistApiV1PlaylistIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Playlist
     */
    async deletePlaylistApiV1PlaylistIdDeleteRaw(requestParameters: DeletePlaylistApiV1PlaylistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deletePlaylistApiV1PlaylistIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Playlist
     */
    async deletePlaylistApiV1PlaylistIdDelete(requestParameters: DeletePlaylistApiV1PlaylistIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deletePlaylistApiV1PlaylistIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSongApiV1SongIdDelete without sending the request
     */
    async deleteSongApiV1SongIdDeleteRequestOpts(requestParameters: DeleteSongApiV1SongIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSongApiV1SongIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Song
     */
    async deleteSongApiV1SongIdDeleteRaw(requestParameters: DeleteSongApiV1SongIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResponse>> {
        const requestOptions = await this.deleteSongApiV1SongIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete Song
     */
    async deleteSongApiV1SongIdDelete(requestParameters: DeleteSongApiV1SongIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResponse> {
        const response = await this.deleteSongApiV1SongIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlbumApiV1AlbumIdGet without sending the request
     */
    async getAlbumApiV1AlbumIdGetRequestOpts(requestParameters: GetAlbumApiV1AlbumIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbumApiV1AlbumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Album
     */
    async getAlbumApiV1AlbumIdGetRaw(requestParameters: GetAlbumApiV1AlbumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponse>> {
        const requestOptions = await this.getAlbumApiV1AlbumIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseFromJSON(jsonValue));
    }

    /**
     * Get Album
     */
    async getAlbumApiV1AlbumIdGet(requestParameters: GetAlbumApiV1AlbumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponse> {
        const response = await this.getAlbumApiV1AlbumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet without sending the request
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequestOpts(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/albums`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Albums From Playlist
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRaw(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Albums From Playlist
     */
    async getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet(requestParameters: GetAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getArtistApiV1ArtistIdGet without sending the request
     */
    async getArtistApiV1ArtistIdGetRequestOpts(requestParameters: GetArtistApiV1ArtistIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getArtistApiV1ArtistIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Artist
     */
    async getArtistApiV1ArtistIdGetRaw(requestParameters: GetArtistApiV1ArtistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistResponse>> {
        const requestOptions = await this.getArtistApiV1ArtistIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistResponseFromJSON(jsonValue));
    }

    /**
     * Get Artist
     */
    async getArtistApiV1ArtistIdGet(requestParameters: GetArtistApiV1ArtistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistResponse> {
        const response = await this.getArtistApiV1ArtistIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getArtistsFromPlaylistApiV1PlaylistIdArtistsGet without sending the request
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequestOpts(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getArtistsFromPlaylistApiV1PlaylistIdArtistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/artists`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Artists From Playlist
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRaw(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Artists From Playlist
     */
    async getArtistsFromPlaylistApiV1PlaylistIdArtistsGet(requestParameters: GetArtistsFromPlaylistApiV1PlaylistIdArtistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getArtistsFromPlaylistApiV1PlaylistIdArtistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet without sending the request
     */
    async getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequestOpts(requestParameters: GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/collaborations`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Collaborations From Artist
     */
    async getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRaw(requestParameters: GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Collaborations From Artist
     */
    async getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet(requestParameters: GetCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromAlbumApiV1AlbumIdFeaturesGet without sending the request
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromAlbumApiV1AlbumIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Album
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRaw(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Album
     */
    async getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(requestParameters: GetFeaturesFromAlbumApiV1AlbumIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromAlbumApiV1AlbumIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromArtistApiV1ArtistIdFeaturesGet without sending the request
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromArtistApiV1ArtistIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Artist
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGetRaw(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromArtistApiV1ArtistIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Artist
     */
    async getFeaturesFromArtistApiV1ArtistIdFeaturesGet(requestParameters: GetFeaturesFromArtistApiV1ArtistIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromArtistApiV1ArtistIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeaturesFromSongApiV1SongIdFeaturesGet without sending the request
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGetRequestOpts(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeaturesFromSongApiV1SongIdFeaturesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/features`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Features From Song
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGetRaw(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getFeaturesFromSongApiV1SongIdFeaturesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Features From Song
     */
    async getFeaturesFromSongApiV1SongIdFeaturesGet(requestParameters: GetFeaturesFromSongApiV1SongIdFeaturesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFeaturesFromSongApiV1SongIdFeaturesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenreApiV1GenreIdGet without sending the request
     */
    async getGenreApiV1GenreIdGetRequestOpts(requestParameters: GetGenreApiV1GenreIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenreApiV1GenreIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genre/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genre
     */
    async getGenreApiV1GenreIdGetRaw(requestParameters: GetGenreApiV1GenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenreResponse>> {
        const requestOptions = await this.getGenreApiV1GenreIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenreResponseFromJSON(jsonValue));
    }

    /**
     * Get Genre
     */
    async getGenreApiV1GenreIdGet(requestParameters: GetGenreApiV1GenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenreResponse> {
        const response = await this.getGenreApiV1GenreIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenresFromAlbumApiV1AlbumIdGenresGet without sending the request
     */
    async getGenresFromAlbumApiV1AlbumIdGenresGetRequestOpts(requestParameters: GetGenresFromAlbumApiV1AlbumIdGenresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenresFromAlbumApiV1AlbumIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/genres`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genres From Album
     */
    async getGenresFromAlbumApiV1AlbumIdGenresGetRaw(requestParameters: GetGenresFromAlbumApiV1AlbumIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getGenresFromAlbumApiV1AlbumIdGenresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Genres From Album
     */
    async getGenresFromAlbumApiV1AlbumIdGenresGet(requestParameters: GetGenresFromAlbumApiV1AlbumIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGenresFromAlbumApiV1AlbumIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenresFromArtistApiV1ArtistIdGenresGet without sending the request
     */
    async getGenresFromArtistApiV1ArtistIdGenresGetRequestOpts(requestParameters: GetGenresFromArtistApiV1ArtistIdGenresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenresFromArtistApiV1ArtistIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/genres`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genres From Artist
     */
    async getGenresFromArtistApiV1ArtistIdGenresGetRaw(requestParameters: GetGenresFromArtistApiV1ArtistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getGenresFromArtistApiV1ArtistIdGenresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Genres From Artist
     */
    async getGenresFromArtistApiV1ArtistIdGenresGet(requestParameters: GetGenresFromArtistApiV1ArtistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGenresFromArtistApiV1ArtistIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenresFromPlaylistApiV1PlaylistIdGenresGet without sending the request
     */
    async getGenresFromPlaylistApiV1PlaylistIdGenresGetRequestOpts(requestParameters: GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGenresFromPlaylistApiV1PlaylistIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/genres`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genres From Playlist
     */
    async getGenresFromPlaylistApiV1PlaylistIdGenresGetRaw(requestParameters: GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getGenresFromPlaylistApiV1PlaylistIdGenresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Genres From Playlist
     */
    async getGenresFromPlaylistApiV1PlaylistIdGenresGet(requestParameters: GetGenresFromPlaylistApiV1PlaylistIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGenresFromPlaylistApiV1PlaylistIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getImageApiV1ImageIdGet without sending the request
     */
    async getImageApiV1ImageIdGetRequestOpts(requestParameters: GetImageApiV1ImageIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getImageApiV1ImageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/image/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Image
     */
    async getImageApiV1ImageIdGetRaw(requestParameters: GetImageApiV1ImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getImageApiV1ImageIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get Image
     */
    async getImageApiV1ImageIdGet(requestParameters: GetImageApiV1ImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getImageApiV1ImageIdGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPlaylistApiV1PlaylistIdGet without sending the request
     */
    async getPlaylistApiV1PlaylistIdGetRequestOpts(requestParameters: GetPlaylistApiV1PlaylistIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlaylistApiV1PlaylistIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Playlist
     */
    async getPlaylistApiV1PlaylistIdGetRaw(requestParameters: GetPlaylistApiV1PlaylistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistResponse>> {
        const requestOptions = await this.getPlaylistApiV1PlaylistIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistResponseFromJSON(jsonValue));
    }

    /**
     * Get Playlist
     */
    async getPlaylistApiV1PlaylistIdGet(requestParameters: GetPlaylistApiV1PlaylistIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistResponse> {
        const response = await this.getPlaylistApiV1PlaylistIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet without sending the request
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequestOpts(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/playlists`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Playlists Song Is Part Of
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRaw(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Playlists Song Is Part Of
     */
    async getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet(requestParameters: GetPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongApiV1SongIdGet without sending the request
     */
    async getSongApiV1SongIdGetRequestOpts(requestParameters: GetSongApiV1SongIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongApiV1SongIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Song
     */
    async getSongApiV1SongIdGetRaw(requestParameters: GetSongApiV1SongIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SongResponse>> {
        const requestOptions = await this.getSongApiV1SongIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongResponseFromJSON(jsonValue));
    }

    /**
     * Get Song
     */
    async getSongApiV1SongIdGet(requestParameters: GetSongApiV1SongIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SongResponse> {
        const response = await this.getSongApiV1SongIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromAlbumApiV1AlbumIdSongsGet without sending the request
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGetRequestOpts(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromAlbumApiV1AlbumIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/album/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Album
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGetRaw(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromAlbumApiV1AlbumIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Album
     */
    async getSongsFromAlbumApiV1AlbumIdSongsGet(requestParameters: GetSongsFromAlbumApiV1AlbumIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromAlbumApiV1AlbumIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromArtistApiV1ArtistIdSongsGet without sending the request
     */
    async getSongsFromArtistApiV1ArtistIdSongsGetRequestOpts(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromArtistApiV1ArtistIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artist/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Artist
     */
    async getSongsFromArtistApiV1ArtistIdSongsGetRaw(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromArtistApiV1ArtistIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Artist
     */
    async getSongsFromArtistApiV1ArtistIdSongsGet(requestParameters: GetSongsFromArtistApiV1ArtistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromArtistApiV1ArtistIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromGenreApiV1GenreIdSongsGet without sending the request
     */
    async getSongsFromGenreApiV1GenreIdSongsGetRequestOpts(requestParameters: GetSongsFromGenreApiV1GenreIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromGenreApiV1GenreIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genre/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Genre
     */
    async getSongsFromGenreApiV1GenreIdSongsGetRaw(requestParameters: GetSongsFromGenreApiV1GenreIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromGenreApiV1GenreIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Genre
     */
    async getSongsFromGenreApiV1GenreIdSongsGet(requestParameters: GetSongsFromGenreApiV1GenreIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromGenreApiV1GenreIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSongsFromPlaylistApiV1PlaylistIdSongsGet without sending the request
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGetRequestOpts(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSongsFromPlaylistApiV1PlaylistIdSongsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlist/{id}/songs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Songs From Playlist
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGetRaw(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getSongsFromPlaylistApiV1PlaylistIdSongsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Songs From Playlist
     */
    async getSongsFromPlaylistApiV1PlaylistIdSongsGet(requestParameters: GetSongsFromPlaylistApiV1PlaylistIdSongsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getSongsFromPlaylistApiV1PlaylistIdSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllAlbumsApiV1AlbumsGet without sending the request
     */
    async listAllAlbumsApiV1AlbumsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/albums`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Albums
     */
    async listAllAlbumsApiV1AlbumsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlbumResponse>>> {
        const requestOptions = await this.listAllAlbumsApiV1AlbumsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumResponseFromJSON));
    }

    /**
     * List All Albums
     */
    async listAllAlbumsApiV1AlbumsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlbumResponse>> {
        const response = await this.listAllAlbumsApiV1AlbumsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllArtistApiV1ArtistsGet without sending the request
     */
    async listAllArtistApiV1ArtistsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/artists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Artist
     */
    async listAllArtistApiV1ArtistsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ArtistResponse>>> {
        const requestOptions = await this.listAllArtistApiV1ArtistsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ArtistResponseFromJSON));
    }

    /**
     * List All Artist
     */
    async listAllArtistApiV1ArtistsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ArtistResponse>> {
        const response = await this.listAllArtistApiV1ArtistsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllGenresApiV1GenresGet without sending the request
     */
    async listAllGenresApiV1GenresGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genres`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Genres
     */
    async listAllGenresApiV1GenresGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GenreResponse>>> {
        const requestOptions = await this.listAllGenresApiV1GenresGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GenreResponseFromJSON));
    }

    /**
     * List All Genres
     */
    async listAllGenresApiV1GenresGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GenreResponse>> {
        const response = await this.listAllGenresApiV1GenresGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllPlaylistsApiV1PlaylistsGet without sending the request
     */
    async listAllPlaylistsApiV1PlaylistsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/playlists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Playlists
     */
    async listAllPlaylistsApiV1PlaylistsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistResponse>>> {
        const requestOptions = await this.listAllPlaylistsApiV1PlaylistsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistResponseFromJSON));
    }

    /**
     * List All Playlists
     */
    async listAllPlaylistsApiV1PlaylistsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistResponse>> {
        const response = await this.listAllPlaylistsApiV1PlaylistsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAllSongApiV1SongsGet without sending the request
     */
    async listAllSongApiV1SongsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/songs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List All Song
     */
    async listAllSongApiV1SongsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SongResponse>>> {
        const requestOptions = await this.listAllSongApiV1SongsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SongResponseFromJSON));
    }

    /**
     * List All Song
     */
    async listAllSongApiV1SongsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SongResponse>> {
        const response = await this.listAllSongApiV1SongsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setDatabaseApiV1DbPatch without sending the request
     */
    async setDatabaseApiV1DbPatchRequestOpts(requestParameters: SetDatabaseApiV1DbPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling setDatabaseApiV1DbPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/db`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Set Database
     */
    async setDatabaseApiV1DbPatchRaw(requestParameters: SetDatabaseApiV1DbPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const requestOptions = await this.setDatabaseApiV1DbPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Set Database
     */
    async setDatabaseApiV1DbPatch(requestParameters: SetDatabaseApiV1DbPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.setDatabaseApiV1DbPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamSongApiV1SongIdStreamGet without sending the request
     */
    async streamSongApiV1SongIdStreamGetRequestOpts(requestParameters: StreamSongApiV1SongIdStreamGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling streamSongApiV1SongIdStreamGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/song/{id}/stream`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stream Song
     */
    async streamSongApiV1SongIdStreamGetRaw(requestParameters: StreamSongApiV1SongIdStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.streamSongApiV1SongIdStreamGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stream Song
     */
    async streamSongApiV1SongIdStreamGet(requestParameters: StreamSongApiV1SongIdStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.streamSongApiV1SongIdStreamGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateAlbumApiV1AlbumIdPatch without sending the request
     */
    async updateAlbumApiV1AlbumIdPatchRequestOpts(requestParameters: UpdateAlbumApiV1AlbumIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAlbumApiV1AlbumIdPatch().'
            );
        }

        if (requestParameters['albumUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'albumUpdateRequest',
                'Required parameter "albumUpdateRequest" was null or undefined when calling updateAlbumApiV1AlbumIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/album/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumUpdateRequestToJSON(requestParameters['albumUpdateRequest']),
        };
    }

    /**
     * Update Album
     */
    async updateAlbumApiV1AlbumIdPatchRaw(requestParameters: UpdateAlbumApiV1AlbumIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponse>> {
        const requestOptions = await this.updateAlbumApiV1AlbumIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseFromJSON(jsonValue));
    }

    /**
     * Update Album
     */
    async updateAlbumApiV1AlbumIdPatch(requestParameters: UpdateAlbumApiV1AlbumIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponse> {
        const response = await this.updateAlbumApiV1AlbumIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateArtistApiV1ArtistIdPatch without sending the request
     */
    async updateArtistApiV1ArtistIdPatchRequestOpts(requestParameters: UpdateArtistApiV1ArtistIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateArtistApiV1ArtistIdPatch().'
            );
        }

        if (requestParameters['artistUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'artistUpdateRequest',
                'Required parameter "artistUpdateRequest" was null or undefined when calling updateArtistApiV1ArtistIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/artist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistUpdateRequestToJSON(requestParameters['artistUpdateRequest']),
        };
    }

    /**
     * Update Artist
     */
    async updateArtistApiV1ArtistIdPatchRaw(requestParameters: UpdateArtistApiV1ArtistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistResponse>> {
        const requestOptions = await this.updateArtistApiV1ArtistIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistResponseFromJSON(jsonValue));
    }

    /**
     * Update Artist
     */
    async updateArtistApiV1ArtistIdPatch(requestParameters: UpdateArtistApiV1ArtistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistResponse> {
        const response = await this.updateArtistApiV1ArtistIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateGenreApiV1GenreIdPatch without sending the request
     */
    async updateGenreApiV1GenreIdPatchRequestOpts(requestParameters: UpdateGenreApiV1GenreIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateGenreApiV1GenreIdPatch().'
            );
        }

        if (requestParameters['genreUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'genreUpdateRequest',
                'Required parameter "genreUpdateRequest" was null or undefined when calling updateGenreApiV1GenreIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/genre/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GenreUpdateRequestToJSON(requestParameters['genreUpdateRequest']),
        };
    }

    /**
     * Update Genre
     */
    async updateGenreApiV1GenreIdPatchRaw(requestParameters: UpdateGenreApiV1GenreIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenreResponse>> {
        const requestOptions = await this.updateGenreApiV1GenreIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenreResponseFromJSON(jsonValue));
    }

    /**
     * Update Genre
     */
    async updateGenreApiV1GenreIdPatch(requestParameters: UpdateGenreApiV1GenreIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenreResponse> {
        const response = await this.updateGenreApiV1GenreIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePlaylistApiV1PlaylistIdPatch without sending the request
     */
    async updatePlaylistApiV1PlaylistIdPatchRequestOpts(requestParameters: UpdatePlaylistApiV1PlaylistIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePlaylistApiV1PlaylistIdPatch().'
            );
        }

        if (requestParameters['playlistUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'playlistUpdateRequest',
                'Required parameter "playlistUpdateRequest" was null or undefined when calling updatePlaylistApiV1PlaylistIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/playlist/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PlaylistUpdateRequestToJSON(requestParameters['playlistUpdateRequest']),
        };
    }

    /**
     * Update Playlist
     */
    async updatePlaylistApiV1PlaylistIdPatchRaw(requestParameters: UpdatePlaylistApiV1PlaylistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistResponse>> {
        const requestOptions = await this.updatePlaylistApiV1PlaylistIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistResponseFromJSON(jsonValue));
    }

    /**
     * Update Playlist
     */
    async updatePlaylistApiV1PlaylistIdPatch(requestParameters: UpdatePlaylistApiV1PlaylistIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistResponse> {
        const response = await this.updatePlaylistApiV1PlaylistIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSongApiV1SongIdPatch without sending the request
     */
    async updateSongApiV1SongIdPatchRequestOpts(requestParameters: UpdateSongApiV1SongIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSongApiV1SongIdPatch().'
            );
        }

        if (requestParameters['songUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'songUpdateRequest',
                'Required parameter "songUpdateRequest" was null or undefined when calling updateSongApiV1SongIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/song/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SongUpdateRequestToJSON(requestParameters['songUpdateRequest']),
        };
    }

    /**
     * Update Song
     */
    async updateSongApiV1SongIdPatchRaw(requestParameters: UpdateSongApiV1SongIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SongResponse>> {
        const requestOptions = await this.updateSongApiV1SongIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongResponseFromJSON(jsonValue));
    }

    /**
     * Update Song
     */
    async updateSongApiV1SongIdPatch(requestParameters: UpdateSongApiV1SongIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SongResponse> {
        const response = await this.updateSongApiV1SongIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadSongApiV1SongPost without sending the request
     */
    async uploadSongApiV1SongPostRequestOpts(requestParameters: UploadSongApiV1SongPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadSongApiV1SongPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/v1/song`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload Song
     */
    async uploadSongApiV1SongPostRaw(requestParameters: UploadSongApiV1SongPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SongResponse>> {
        const requestOptions = await this.uploadSongApiV1SongPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongResponseFromJSON(jsonValue));
    }

    /**
     * Upload Song
     */
    async uploadSongApiV1SongPost(requestParameters: UploadSongApiV1SongPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SongResponse> {
        const response = await this.uploadSongApiV1SongPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
