/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AlbumCreateRequest from './model/AlbumCreateRequest';
import AlbumResponse from './model/AlbumResponse';
import AlbumUpdateRequest from './model/AlbumUpdateRequest';
import ArtistCreateRequest from './model/ArtistCreateRequest';
import ArtistResponse from './model/ArtistResponse';
import ArtistUpdateRequest from './model/ArtistUpdateRequest';
import DeletedResponse from './model/DeletedResponse';
import GenreCreateRequest from './model/GenreCreateRequest';
import GenreUpdateRequest from './model/GenreUpdateRequest';
import HTTPValidationError from './model/HTTPValidationError';
import LocationInner from './model/LocationInner';
import PlaylistCreateRequest from './model/PlaylistCreateRequest';
import PlaylistResponse from './model/PlaylistResponse';
import PlaylistUpdateRequest from './model/PlaylistUpdateRequest';
import SongResponse from './model/SongResponse';
import SongUpdateRequest from './model/SongUpdateRequest';
import ValidationError from './model/ValidationError';
import AlbumApi from './api/AlbumApi';
import ArtistApi from './api/ArtistApi';
import DatabaseApi from './api/DatabaseApi';
import DefaultApi from './api/DefaultApi';
import GenreApi from './api/GenreApi';
import ImageApi from './api/ImageApi';
import PlaylistApi from './api/PlaylistApi';
import SongApi from './api/SongApi';
import V1Api from './api/V1Api';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AudioServer = require('index'); // See note below*.
* var xxxSvc = new AudioServer.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AudioServer.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AudioServer.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AudioServer.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AlbumCreateRequest model constructor.
     * @property {module:model/AlbumCreateRequest}
     */
    AlbumCreateRequest,

    /**
     * The AlbumResponse model constructor.
     * @property {module:model/AlbumResponse}
     */
    AlbumResponse,

    /**
     * The AlbumUpdateRequest model constructor.
     * @property {module:model/AlbumUpdateRequest}
     */
    AlbumUpdateRequest,

    /**
     * The ArtistCreateRequest model constructor.
     * @property {module:model/ArtistCreateRequest}
     */
    ArtistCreateRequest,

    /**
     * The ArtistResponse model constructor.
     * @property {module:model/ArtistResponse}
     */
    ArtistResponse,

    /**
     * The ArtistUpdateRequest model constructor.
     * @property {module:model/ArtistUpdateRequest}
     */
    ArtistUpdateRequest,

    /**
     * The DeletedResponse model constructor.
     * @property {module:model/DeletedResponse}
     */
    DeletedResponse,

    /**
     * The GenreCreateRequest model constructor.
     * @property {module:model/GenreCreateRequest}
     */
    GenreCreateRequest,

    /**
     * The GenreUpdateRequest model constructor.
     * @property {module:model/GenreUpdateRequest}
     */
    GenreUpdateRequest,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The LocationInner model constructor.
     * @property {module:model/LocationInner}
     */
    LocationInner,

    /**
     * The PlaylistCreateRequest model constructor.
     * @property {module:model/PlaylistCreateRequest}
     */
    PlaylistCreateRequest,

    /**
     * The PlaylistResponse model constructor.
     * @property {module:model/PlaylistResponse}
     */
    PlaylistResponse,

    /**
     * The PlaylistUpdateRequest model constructor.
     * @property {module:model/PlaylistUpdateRequest}
     */
    PlaylistUpdateRequest,

    /**
     * The SongResponse model constructor.
     * @property {module:model/SongResponse}
     */
    SongResponse,

    /**
     * The SongUpdateRequest model constructor.
     * @property {module:model/SongUpdateRequest}
     */
    SongUpdateRequest,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AlbumApi service constructor.
    * @property {module:api/AlbumApi}
    */
    AlbumApi,

    /**
    * The ArtistApi service constructor.
    * @property {module:api/ArtistApi}
    */
    ArtistApi,

    /**
    * The DatabaseApi service constructor.
    * @property {module:api/DatabaseApi}
    */
    DatabaseApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The GenreApi service constructor.
    * @property {module:api/GenreApi}
    */
    GenreApi,

    /**
    * The ImageApi service constructor.
    * @property {module:api/ImageApi}
    */
    ImageApi,

    /**
    * The PlaylistApi service constructor.
    * @property {module:api/PlaylistApi}
    */
    PlaylistApi,

    /**
    * The SongApi service constructor.
    * @property {module:api/SongApi}
    */
    SongApi,

    /**
    * The V1Api service constructor.
    * @property {module:api/V1Api}
    */
    V1Api
};
