/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlbumCreateRequest from '../model/AlbumCreateRequest';
import AlbumResponse from '../model/AlbumResponse';
import AlbumUpdateRequest from '../model/AlbumUpdateRequest';
import DeletedResponse from '../model/DeletedResponse';
import HTTPValidationError from '../model/HTTPValidationError';

/**
* Album service.
* @module api/AlbumApi
* @version 0.1.0
*/
export default class AlbumApi {

    /**
    * Constructs a new AlbumApi. 
    * @alias module:api/AlbumApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createAlbumApiV1AlbumPost operation.
     * @callback module:api/AlbumApi~createAlbumApiV1AlbumPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Album
     * @param {module:model/AlbumCreateRequest} albumCreateRequest 
     * @param {module:api/AlbumApi~createAlbumApiV1AlbumPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumResponse}
     */
    createAlbumApiV1AlbumPost(albumCreateRequest, callback) {
      let postBody = albumCreateRequest;
      // verify the required parameter 'albumCreateRequest' is set
      if (albumCreateRequest === undefined || albumCreateRequest === null) {
        throw new Error("Missing the required parameter 'albumCreateRequest' when calling createAlbumApiV1AlbumPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AlbumResponse;
      return this.apiClient.callApi(
        '/api/v1/album', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAlbumApiV1AlbumIdDelete operation.
     * @callback module:api/AlbumApi~deleteAlbumApiV1AlbumIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Album
     * @param {Number} id 
     * @param {module:api/AlbumApi~deleteAlbumApiV1AlbumIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteAlbumApiV1AlbumIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAlbumApiV1AlbumIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/album/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlbumApiV1AlbumIdGet operation.
     * @callback module:api/AlbumApi~getAlbumApiV1AlbumIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Album
     * @param {Number} id 
     * @param {module:api/AlbumApi~getAlbumApiV1AlbumIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumResponse}
     */
    getAlbumApiV1AlbumIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAlbumApiV1AlbumIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AlbumResponse;
      return this.apiClient.callApi(
        '/api/v1/album/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet operation.
     * @callback module:api/AlbumApi~getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Albums From Playlist
     * @param {Number} id 
     * @param {module:api/AlbumApi~getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/albums', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromAlbumApiV1AlbumIdFeaturesGet operation.
     * @callback module:api/AlbumApi~getFeaturesFromAlbumApiV1AlbumIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Album
     * @param {Number} id 
     * @param {module:api/AlbumApi~getFeaturesFromAlbumApiV1AlbumIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromAlbumApiV1AlbumIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGenresFromAlbumApiV1AlbumIdGenresGet operation.
     * @callback module:api/AlbumApi~getGenresFromAlbumApiV1AlbumIdGenresGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Genres From Album
     * @param {Number} id 
     * @param {module:api/AlbumApi~getGenresFromAlbumApiV1AlbumIdGenresGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getGenresFromAlbumApiV1AlbumIdGenresGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGenresFromAlbumApiV1AlbumIdGenresGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/genres', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromAlbumApiV1AlbumIdSongsGet operation.
     * @callback module:api/AlbumApi~getSongsFromAlbumApiV1AlbumIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Album
     * @param {Number} id 
     * @param {module:api/AlbumApi~getSongsFromAlbumApiV1AlbumIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromAlbumApiV1AlbumIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromAlbumApiV1AlbumIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllAlbumsApiV1AlbumsGet operation.
     * @callback module:api/AlbumApi~listAllAlbumsApiV1AlbumsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlbumResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Albums
     * @param {module:api/AlbumApi~listAllAlbumsApiV1AlbumsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlbumResponse>}
     */
    listAllAlbumsApiV1AlbumsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlbumResponse];
      return this.apiClient.callApi(
        '/api/v1/albums', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateAlbumApiV1AlbumIdPatch operation.
     * @callback module:api/AlbumApi~updateAlbumApiV1AlbumIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Album
     * @param {Number} id 
     * @param {module:model/AlbumUpdateRequest} albumUpdateRequest 
     * @param {module:api/AlbumApi~updateAlbumApiV1AlbumIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumResponse}
     */
    updateAlbumApiV1AlbumIdPatch(id, albumUpdateRequest, callback) {
      let postBody = albumUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateAlbumApiV1AlbumIdPatch");
      }
      // verify the required parameter 'albumUpdateRequest' is set
      if (albumUpdateRequest === undefined || albumUpdateRequest === null) {
        throw new Error("Missing the required parameter 'albumUpdateRequest' when calling updateAlbumApiV1AlbumIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AlbumResponse;
      return this.apiClient.callApi(
        '/api/v1/album/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
