/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ArtistCreateRequest from '../model/ArtistCreateRequest';
import ArtistResponse from '../model/ArtistResponse';
import ArtistUpdateRequest from '../model/ArtistUpdateRequest';
import DeletedResponse from '../model/DeletedResponse';
import HTTPValidationError from '../model/HTTPValidationError';

/**
* Artist service.
* @module api/ArtistApi
* @version 0.1.0
*/
export default class ArtistApi {

    /**
    * Constructs a new ArtistApi. 
    * @alias module:api/ArtistApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createArtistApiV1ArtistPost operation.
     * @callback module:api/ArtistApi~createArtistApiV1ArtistPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArtistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Artist
     * @param {module:model/ArtistCreateRequest} artistCreateRequest 
     * @param {module:api/ArtistApi~createArtistApiV1ArtistPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArtistResponse}
     */
    createArtistApiV1ArtistPost(artistCreateRequest, callback) {
      let postBody = artistCreateRequest;
      // verify the required parameter 'artistCreateRequest' is set
      if (artistCreateRequest === undefined || artistCreateRequest === null) {
        throw new Error("Missing the required parameter 'artistCreateRequest' when calling createArtistApiV1ArtistPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ArtistResponse;
      return this.apiClient.callApi(
        '/api/v1/artist', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteArtistApiV1ArtistIdDelete operation.
     * @callback module:api/ArtistApi~deleteArtistApiV1ArtistIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Artist
     * @param {Number} id 
     * @param {module:api/ArtistApi~deleteArtistApiV1ArtistIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteArtistApiV1ArtistIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteArtistApiV1ArtistIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/artist/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtistApiV1ArtistIdGet operation.
     * @callback module:api/ArtistApi~getArtistApiV1ArtistIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArtistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artist
     * @param {Number} id 
     * @param {module:api/ArtistApi~getArtistApiV1ArtistIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArtistResponse}
     */
    getArtistApiV1ArtistIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getArtistApiV1ArtistIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ArtistResponse;
      return this.apiClient.callApi(
        '/api/v1/artist/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtistsFromPlaylistApiV1PlaylistIdArtistsGet operation.
     * @callback module:api/ArtistApi~getArtistsFromPlaylistApiV1PlaylistIdArtistsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artists From Playlist
     * @param {Number} id 
     * @param {module:api/ArtistApi~getArtistsFromPlaylistApiV1PlaylistIdArtistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getArtistsFromPlaylistApiV1PlaylistIdArtistsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getArtistsFromPlaylistApiV1PlaylistIdArtistsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/artists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet operation.
     * @callback module:api/ArtistApi~getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Collaborations From Artist
     * @param {Number} id 
     * @param {module:api/ArtistApi~getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/collaborations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromAlbumApiV1AlbumIdFeaturesGet operation.
     * @callback module:api/ArtistApi~getFeaturesFromAlbumApiV1AlbumIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Album
     * @param {Number} id 
     * @param {module:api/ArtistApi~getFeaturesFromAlbumApiV1AlbumIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromAlbumApiV1AlbumIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromArtistApiV1ArtistIdFeaturesGet operation.
     * @callback module:api/ArtistApi~getFeaturesFromArtistApiV1ArtistIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Artist
     * @param {Number} id 
     * @param {module:api/ArtistApi~getFeaturesFromArtistApiV1ArtistIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromArtistApiV1ArtistIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromArtistApiV1ArtistIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromSongApiV1SongIdFeaturesGet operation.
     * @callback module:api/ArtistApi~getFeaturesFromSongApiV1SongIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Song
     * @param {Number} id 
     * @param {module:api/ArtistApi~getFeaturesFromSongApiV1SongIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromSongApiV1SongIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromSongApiV1SongIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/song/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGenresFromArtistApiV1ArtistIdGenresGet operation.
     * @callback module:api/ArtistApi~getGenresFromArtistApiV1ArtistIdGenresGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Genres From Artist
     * @param {Number} id 
     * @param {module:api/ArtistApi~getGenresFromArtistApiV1ArtistIdGenresGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getGenresFromArtistApiV1ArtistIdGenresGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGenresFromArtistApiV1ArtistIdGenresGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/genres', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromArtistApiV1ArtistIdSongsGet operation.
     * @callback module:api/ArtistApi~getSongsFromArtistApiV1ArtistIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Artist
     * @param {Number} id 
     * @param {module:api/ArtistApi~getSongsFromArtistApiV1ArtistIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromArtistApiV1ArtistIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromArtistApiV1ArtistIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllArtistApiV1ArtistsGet operation.
     * @callback module:api/ArtistApi~listAllArtistApiV1ArtistsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ArtistResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Artist
     * @param {module:api/ArtistApi~listAllArtistApiV1ArtistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ArtistResponse>}
     */
    listAllArtistApiV1ArtistsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ArtistResponse];
      return this.apiClient.callApi(
        '/api/v1/artists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateArtistApiV1ArtistIdPatch operation.
     * @callback module:api/ArtistApi~updateArtistApiV1ArtistIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArtistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Artist
     * @param {Number} id 
     * @param {module:model/ArtistUpdateRequest} artistUpdateRequest 
     * @param {module:api/ArtistApi~updateArtistApiV1ArtistIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArtistResponse}
     */
    updateArtistApiV1ArtistIdPatch(id, artistUpdateRequest, callback) {
      let postBody = artistUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateArtistApiV1ArtistIdPatch");
      }
      // verify the required parameter 'artistUpdateRequest' is set
      if (artistUpdateRequest === undefined || artistUpdateRequest === null) {
        throw new Error("Missing the required parameter 'artistUpdateRequest' when calling updateArtistApiV1ArtistIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ArtistResponse;
      return this.apiClient.callApi(
        '/api/v1/artist/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
