/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeletedResponse from '../model/DeletedResponse';
import HTTPValidationError from '../model/HTTPValidationError';
import SongResponse from '../model/SongResponse';
import SongUpdateRequest from '../model/SongUpdateRequest';

/**
* Song service.
* @module api/SongApi
* @version 0.1.0
*/
export default class SongApi {

    /**
    * Constructs a new SongApi. 
    * @alias module:api/SongApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteSongApiV1SongIdDelete operation.
     * @callback module:api/SongApi~deleteSongApiV1SongIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Song
     * @param {Number} id 
     * @param {module:api/SongApi~deleteSongApiV1SongIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteSongApiV1SongIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteSongApiV1SongIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/song/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromArtistApiV1ArtistIdFeaturesGet operation.
     * @callback module:api/SongApi~getFeaturesFromArtistApiV1ArtistIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Artist
     * @param {Number} id 
     * @param {module:api/SongApi~getFeaturesFromArtistApiV1ArtistIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromArtistApiV1ArtistIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromArtistApiV1ArtistIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromSongApiV1SongIdFeaturesGet operation.
     * @callback module:api/SongApi~getFeaturesFromSongApiV1SongIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Song
     * @param {Number} id 
     * @param {module:api/SongApi~getFeaturesFromSongApiV1SongIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromSongApiV1SongIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromSongApiV1SongIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/song/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet operation.
     * @callback module:api/SongApi~getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Playlists Song Is Part Of
     * @param {Number} id 
     * @param {module:api/SongApi~getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/song/{id}/playlists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongApiV1SongIdGet operation.
     * @callback module:api/SongApi~getSongApiV1SongIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SongResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Song
     * @param {Number} id 
     * @param {module:api/SongApi~getSongApiV1SongIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongResponse}
     */
    getSongApiV1SongIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongApiV1SongIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SongResponse;
      return this.apiClient.callApi(
        '/api/v1/song/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromAlbumApiV1AlbumIdSongsGet operation.
     * @callback module:api/SongApi~getSongsFromAlbumApiV1AlbumIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Album
     * @param {Number} id 
     * @param {module:api/SongApi~getSongsFromAlbumApiV1AlbumIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromAlbumApiV1AlbumIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromAlbumApiV1AlbumIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromArtistApiV1ArtistIdSongsGet operation.
     * @callback module:api/SongApi~getSongsFromArtistApiV1ArtistIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Artist
     * @param {Number} id 
     * @param {module:api/SongApi~getSongsFromArtistApiV1ArtistIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromArtistApiV1ArtistIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromArtistApiV1ArtistIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromGenreApiV1GenreSongsGet operation.
     * @callback module:api/SongApi~getSongsFromGenreApiV1GenreSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Genre
     * @param {String} name 
     * @param {module:api/SongApi~getSongsFromGenreApiV1GenreSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromGenreApiV1GenreSongsGet(name, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getSongsFromGenreApiV1GenreSongsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/genre/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromPlaylistApiV1PlaylistIdSongsGet operation.
     * @callback module:api/SongApi~getSongsFromPlaylistApiV1PlaylistIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Playlist
     * @param {Number} id 
     * @param {module:api/SongApi~getSongsFromPlaylistApiV1PlaylistIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromPlaylistApiV1PlaylistIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromPlaylistApiV1PlaylistIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllSongApiV1SongsGet operation.
     * @callback module:api/SongApi~listAllSongApiV1SongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Song
     * @param {module:api/SongApi~listAllSongApiV1SongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongResponse>}
     */
    listAllSongApiV1SongsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SongResponse];
      return this.apiClient.callApi(
        '/api/v1/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the streamSongApiV1SongIdStreamGet operation.
     * @callback module:api/SongApi~streamSongApiV1SongIdStreamGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Stream Song
     * @param {Number} id 
     * @param {module:api/SongApi~streamSongApiV1SongIdStreamGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    streamSongApiV1SongIdStreamGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling streamSongApiV1SongIdStreamGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/song/{id}/stream', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSongApiV1SongIdPatch operation.
     * @callback module:api/SongApi~updateSongApiV1SongIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SongResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Song
     * @param {Number} id 
     * @param {module:model/SongUpdateRequest} songUpdateRequest 
     * @param {module:api/SongApi~updateSongApiV1SongIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongResponse}
     */
    updateSongApiV1SongIdPatch(id, songUpdateRequest, callback) {
      let postBody = songUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateSongApiV1SongIdPatch");
      }
      // verify the required parameter 'songUpdateRequest' is set
      if (songUpdateRequest === undefined || songUpdateRequest === null) {
        throw new Error("Missing the required parameter 'songUpdateRequest' when calling updateSongApiV1SongIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SongResponse;
      return this.apiClient.callApi(
        '/api/v1/song/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the uploadSongApiV1SongPost operation.
     * @callback module:api/SongApi~uploadSongApiV1SongPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SongResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload Song
     * @param {String} file 
     * @param {module:api/SongApi~uploadSongApiV1SongPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongResponse}
     */
    uploadSongApiV1SongPost(file, callback) {
      let postBody = null;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling uploadSongApiV1SongPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = SongResponse;
      return this.apiClient.callApi(
        '/api/v1/song', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
