/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlbumCreateRequest from '../model/AlbumCreateRequest';
import AlbumResponse from '../model/AlbumResponse';
import AlbumUpdateRequest from '../model/AlbumUpdateRequest';
import ArtistCreateRequest from '../model/ArtistCreateRequest';
import ArtistResponse from '../model/ArtistResponse';
import ArtistUpdateRequest from '../model/ArtistUpdateRequest';
import DeletedResponse from '../model/DeletedResponse';
import GenreCreateRequest from '../model/GenreCreateRequest';
import GenreUpdateRequest from '../model/GenreUpdateRequest';
import HTTPValidationError from '../model/HTTPValidationError';
import PlaylistCreateRequest from '../model/PlaylistCreateRequest';
import PlaylistResponse from '../model/PlaylistResponse';
import PlaylistUpdateRequest from '../model/PlaylistUpdateRequest';
import SongResponse from '../model/SongResponse';
import SongUpdateRequest from '../model/SongUpdateRequest';

/**
* V1 service.
* @module api/V1Api
* @version 0.1.0
*/
export default class V1Api {

    /**
    * Constructs a new V1Api. 
    * @alias module:api/V1Api
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addImageApiV1ImagePost operation.
     * @callback module:api/V1Api~addImageApiV1ImagePostCallback
     * @param {String} error Error message, if any.
     * @param {Number} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Image
     * @param {String} file 
     * @param {module:api/V1Api~addImageApiV1ImagePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Number}
     */
    addImageApiV1ImagePost(file, callback) {
      let postBody = null;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling addImageApiV1ImagePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = 'Number';
      return this.apiClient.callApi(
        '/api/v1/image', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createAlbumApiV1AlbumPost operation.
     * @callback module:api/V1Api~createAlbumApiV1AlbumPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Album
     * @param {module:model/AlbumCreateRequest} albumCreateRequest 
     * @param {module:api/V1Api~createAlbumApiV1AlbumPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumResponse}
     */
    createAlbumApiV1AlbumPost(albumCreateRequest, callback) {
      let postBody = albumCreateRequest;
      // verify the required parameter 'albumCreateRequest' is set
      if (albumCreateRequest === undefined || albumCreateRequest === null) {
        throw new Error("Missing the required parameter 'albumCreateRequest' when calling createAlbumApiV1AlbumPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AlbumResponse;
      return this.apiClient.callApi(
        '/api/v1/album', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createArtistApiV1ArtistPost operation.
     * @callback module:api/V1Api~createArtistApiV1ArtistPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArtistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Artist
     * @param {module:model/ArtistCreateRequest} artistCreateRequest 
     * @param {module:api/V1Api~createArtistApiV1ArtistPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArtistResponse}
     */
    createArtistApiV1ArtistPost(artistCreateRequest, callback) {
      let postBody = artistCreateRequest;
      // verify the required parameter 'artistCreateRequest' is set
      if (artistCreateRequest === undefined || artistCreateRequest === null) {
        throw new Error("Missing the required parameter 'artistCreateRequest' when calling createArtistApiV1ArtistPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ArtistResponse;
      return this.apiClient.callApi(
        '/api/v1/artist', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createGenreApiV1GenrePost operation.
     * @callback module:api/V1Api~createGenreApiV1GenrePostCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Genre
     * @param {module:model/GenreCreateRequest} genreCreateRequest 
     * @param {module:api/V1Api~createGenreApiV1GenrePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    createGenreApiV1GenrePost(genreCreateRequest, callback) {
      let postBody = genreCreateRequest;
      // verify the required parameter 'genreCreateRequest' is set
      if (genreCreateRequest === undefined || genreCreateRequest === null) {
        throw new Error("Missing the required parameter 'genreCreateRequest' when calling createGenreApiV1GenrePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/v1/genre', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createPlaylistApiV1PlaylistPost operation.
     * @callback module:api/V1Api~createPlaylistApiV1PlaylistPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Playlist
     * @param {module:model/PlaylistCreateRequest} playlistCreateRequest 
     * @param {module:api/V1Api~createPlaylistApiV1PlaylistPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistResponse}
     */
    createPlaylistApiV1PlaylistPost(playlistCreateRequest, callback) {
      let postBody = playlistCreateRequest;
      // verify the required parameter 'playlistCreateRequest' is set
      if (playlistCreateRequest === undefined || playlistCreateRequest === null) {
        throw new Error("Missing the required parameter 'playlistCreateRequest' when calling createPlaylistApiV1PlaylistPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlaylistResponse;
      return this.apiClient.callApi(
        '/api/v1/playlist', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAlbumApiV1AlbumIdDelete operation.
     * @callback module:api/V1Api~deleteAlbumApiV1AlbumIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Album
     * @param {Number} id 
     * @param {module:api/V1Api~deleteAlbumApiV1AlbumIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteAlbumApiV1AlbumIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAlbumApiV1AlbumIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/album/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteArtistApiV1ArtistIdDelete operation.
     * @callback module:api/V1Api~deleteArtistApiV1ArtistIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Artist
     * @param {Number} id 
     * @param {module:api/V1Api~deleteArtistApiV1ArtistIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteArtistApiV1ArtistIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteArtistApiV1ArtistIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/artist/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteGenreApiV1GenreDelete operation.
     * @callback module:api/V1Api~deleteGenreApiV1GenreDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Genre
     * @param {String} name 
     * @param {module:api/V1Api~deleteGenreApiV1GenreDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteGenreApiV1GenreDelete(name, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling deleteGenreApiV1GenreDelete");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/genre', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteImageApiV1ImageIdDelete operation.
     * @callback module:api/V1Api~deleteImageApiV1ImageIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Image
     * @param {Number} id 
     * @param {module:api/V1Api~deleteImageApiV1ImageIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteImageApiV1ImageIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteImageApiV1ImageIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/image/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePlaylistApiV1PlaylistIdDelete operation.
     * @callback module:api/V1Api~deletePlaylistApiV1PlaylistIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Playlist
     * @param {Number} id 
     * @param {module:api/V1Api~deletePlaylistApiV1PlaylistIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deletePlaylistApiV1PlaylistIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deletePlaylistApiV1PlaylistIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSongApiV1SongIdDelete operation.
     * @callback module:api/V1Api~deleteSongApiV1SongIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Song
     * @param {Number} id 
     * @param {module:api/V1Api~deleteSongApiV1SongIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedResponse}
     */
    deleteSongApiV1SongIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteSongApiV1SongIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedResponse;
      return this.apiClient.callApi(
        '/api/v1/song/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlbumApiV1AlbumIdGet operation.
     * @callback module:api/V1Api~getAlbumApiV1AlbumIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Album
     * @param {Number} id 
     * @param {module:api/V1Api~getAlbumApiV1AlbumIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumResponse}
     */
    getAlbumApiV1AlbumIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAlbumApiV1AlbumIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AlbumResponse;
      return this.apiClient.callApi(
        '/api/v1/album/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet operation.
     * @callback module:api/V1Api~getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Albums From Playlist
     * @param {Number} id 
     * @param {module:api/V1Api~getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/albums', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtistApiV1ArtistIdGet operation.
     * @callback module:api/V1Api~getArtistApiV1ArtistIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArtistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artist
     * @param {Number} id 
     * @param {module:api/V1Api~getArtistApiV1ArtistIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArtistResponse}
     */
    getArtistApiV1ArtistIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getArtistApiV1ArtistIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ArtistResponse;
      return this.apiClient.callApi(
        '/api/v1/artist/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtistsFromPlaylistApiV1PlaylistIdArtistsGet operation.
     * @callback module:api/V1Api~getArtistsFromPlaylistApiV1PlaylistIdArtistsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artists From Playlist
     * @param {Number} id 
     * @param {module:api/V1Api~getArtistsFromPlaylistApiV1PlaylistIdArtistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getArtistsFromPlaylistApiV1PlaylistIdArtistsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getArtistsFromPlaylistApiV1PlaylistIdArtistsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/artists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet operation.
     * @callback module:api/V1Api~getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Collaborations From Artist
     * @param {Number} id 
     * @param {module:api/V1Api~getCollaborationsFromArtistApiV1ArtistIdCollaborationsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/collaborations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromAlbumApiV1AlbumIdFeaturesGet operation.
     * @callback module:api/V1Api~getFeaturesFromAlbumApiV1AlbumIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Album
     * @param {Number} id 
     * @param {module:api/V1Api~getFeaturesFromAlbumApiV1AlbumIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromAlbumApiV1AlbumIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromArtistApiV1ArtistIdFeaturesGet operation.
     * @callback module:api/V1Api~getFeaturesFromArtistApiV1ArtistIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Artist
     * @param {Number} id 
     * @param {module:api/V1Api~getFeaturesFromArtistApiV1ArtistIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromArtistApiV1ArtistIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromArtistApiV1ArtistIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeaturesFromSongApiV1SongIdFeaturesGet operation.
     * @callback module:api/V1Api~getFeaturesFromSongApiV1SongIdFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Features From Song
     * @param {Number} id 
     * @param {module:api/V1Api~getFeaturesFromSongApiV1SongIdFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFeaturesFromSongApiV1SongIdFeaturesGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getFeaturesFromSongApiV1SongIdFeaturesGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/song/{id}/features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGenresFromAlbumApiV1AlbumIdGenresGet operation.
     * @callback module:api/V1Api~getGenresFromAlbumApiV1AlbumIdGenresGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Genres From Album
     * @param {Number} id 
     * @param {module:api/V1Api~getGenresFromAlbumApiV1AlbumIdGenresGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getGenresFromAlbumApiV1AlbumIdGenresGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGenresFromAlbumApiV1AlbumIdGenresGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/genres', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGenresFromArtistApiV1ArtistIdGenresGet operation.
     * @callback module:api/V1Api~getGenresFromArtistApiV1ArtistIdGenresGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Genres From Artist
     * @param {Number} id 
     * @param {module:api/V1Api~getGenresFromArtistApiV1ArtistIdGenresGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getGenresFromArtistApiV1ArtistIdGenresGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGenresFromArtistApiV1ArtistIdGenresGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/genres', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGenresFromPlaylistApiV1PlaylistIdGenresGet operation.
     * @callback module:api/V1Api~getGenresFromPlaylistApiV1PlaylistIdGenresGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Genres From Playlist
     * @param {Number} id 
     * @param {module:api/V1Api~getGenresFromPlaylistApiV1PlaylistIdGenresGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getGenresFromPlaylistApiV1PlaylistIdGenresGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGenresFromPlaylistApiV1PlaylistIdGenresGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/genres', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getImageApiV1ImageIdGet operation.
     * @callback module:api/V1Api~getImageApiV1ImageIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Image
     * @param {Number} id 
     * @param {module:api/V1Api~getImageApiV1ImageIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getImageApiV1ImageIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getImageApiV1ImageIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/image/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPlaylistApiV1PlaylistIdGet operation.
     * @callback module:api/V1Api~getPlaylistApiV1PlaylistIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Playlist
     * @param {Number} id 
     * @param {module:api/V1Api~getPlaylistApiV1PlaylistIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistResponse}
     */
    getPlaylistApiV1PlaylistIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPlaylistApiV1PlaylistIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlaylistResponse;
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet operation.
     * @callback module:api/V1Api~getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Playlists Song Is Part Of
     * @param {Number} id 
     * @param {module:api/V1Api~getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/song/{id}/playlists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongApiV1SongIdGet operation.
     * @callback module:api/V1Api~getSongApiV1SongIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SongResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Song
     * @param {Number} id 
     * @param {module:api/V1Api~getSongApiV1SongIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongResponse}
     */
    getSongApiV1SongIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongApiV1SongIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SongResponse;
      return this.apiClient.callApi(
        '/api/v1/song/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromAlbumApiV1AlbumIdSongsGet operation.
     * @callback module:api/V1Api~getSongsFromAlbumApiV1AlbumIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Album
     * @param {Number} id 
     * @param {module:api/V1Api~getSongsFromAlbumApiV1AlbumIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromAlbumApiV1AlbumIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromAlbumApiV1AlbumIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/album/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromArtistApiV1ArtistIdSongsGet operation.
     * @callback module:api/V1Api~getSongsFromArtistApiV1ArtistIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Artist
     * @param {Number} id 
     * @param {module:api/V1Api~getSongsFromArtistApiV1ArtistIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromArtistApiV1ArtistIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromArtistApiV1ArtistIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/artist/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromGenreApiV1GenreSongsGet operation.
     * @callback module:api/V1Api~getSongsFromGenreApiV1GenreSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Genre
     * @param {String} name 
     * @param {module:api/V1Api~getSongsFromGenreApiV1GenreSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromGenreApiV1GenreSongsGet(name, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getSongsFromGenreApiV1GenreSongsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/genre/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsFromPlaylistApiV1PlaylistIdSongsGet operation.
     * @callback module:api/V1Api~getSongsFromPlaylistApiV1PlaylistIdSongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Songs From Playlist
     * @param {Number} id 
     * @param {module:api/V1Api~getSongsFromPlaylistApiV1PlaylistIdSongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getSongsFromPlaylistApiV1PlaylistIdSongsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsFromPlaylistApiV1PlaylistIdSongsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllAlbumsApiV1AlbumsGet operation.
     * @callback module:api/V1Api~listAllAlbumsApiV1AlbumsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlbumResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Albums
     * @param {module:api/V1Api~listAllAlbumsApiV1AlbumsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlbumResponse>}
     */
    listAllAlbumsApiV1AlbumsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlbumResponse];
      return this.apiClient.callApi(
        '/api/v1/albums', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllArtistApiV1ArtistsGet operation.
     * @callback module:api/V1Api~listAllArtistApiV1ArtistsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ArtistResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Artist
     * @param {module:api/V1Api~listAllArtistApiV1ArtistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ArtistResponse>}
     */
    listAllArtistApiV1ArtistsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ArtistResponse];
      return this.apiClient.callApi(
        '/api/v1/artists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllGenresApiV1GenresGet operation.
     * @callback module:api/V1Api~listAllGenresApiV1GenresGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Genres
     * @param {module:api/V1Api~listAllGenresApiV1GenresGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    listAllGenresApiV1GenresGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/genres', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllPlaylistsApiV1PlaylistsGet operation.
     * @callback module:api/V1Api~listAllPlaylistsApiV1PlaylistsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Playlists
     * @param {module:api/V1Api~listAllPlaylistsApiV1PlaylistsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistResponse}
     */
    listAllPlaylistsApiV1PlaylistsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlaylistResponse;
      return this.apiClient.callApi(
        '/api/v1/playlists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllSongApiV1SongsGet operation.
     * @callback module:api/V1Api~listAllSongApiV1SongsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Song
     * @param {module:api/V1Api~listAllSongApiV1SongsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongResponse>}
     */
    listAllSongApiV1SongsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SongResponse];
      return this.apiClient.callApi(
        '/api/v1/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the setDatabaseApiV1DbPatch operation.
     * @callback module:api/V1Api~setDatabaseApiV1DbPatchCallback
     * @param {String} error Error message, if any.
     * @param {Boolean} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set Database
     * @param {String} path 
     * @param {module:api/V1Api~setDatabaseApiV1DbPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Boolean}
     */
    setDatabaseApiV1DbPatch(path, callback) {
      let postBody = null;
      // verify the required parameter 'path' is set
      if (path === undefined || path === null) {
        throw new Error("Missing the required parameter 'path' when calling setDatabaseApiV1DbPatch");
      }

      let pathParams = {
      };
      let queryParams = {
        'path': path
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/api/v1/db', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the streamSongApiV1SongIdStreamGet operation.
     * @callback module:api/V1Api~streamSongApiV1SongIdStreamGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Stream Song
     * @param {Number} id 
     * @param {module:api/V1Api~streamSongApiV1SongIdStreamGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    streamSongApiV1SongIdStreamGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling streamSongApiV1SongIdStreamGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/song/{id}/stream', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateAlbumApiV1AlbumIdPatch operation.
     * @callback module:api/V1Api~updateAlbumApiV1AlbumIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Album
     * @param {Number} id 
     * @param {module:model/AlbumUpdateRequest} albumUpdateRequest 
     * @param {module:api/V1Api~updateAlbumApiV1AlbumIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumResponse}
     */
    updateAlbumApiV1AlbumIdPatch(id, albumUpdateRequest, callback) {
      let postBody = albumUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateAlbumApiV1AlbumIdPatch");
      }
      // verify the required parameter 'albumUpdateRequest' is set
      if (albumUpdateRequest === undefined || albumUpdateRequest === null) {
        throw new Error("Missing the required parameter 'albumUpdateRequest' when calling updateAlbumApiV1AlbumIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AlbumResponse;
      return this.apiClient.callApi(
        '/api/v1/album/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateArtistApiV1ArtistIdPatch operation.
     * @callback module:api/V1Api~updateArtistApiV1ArtistIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArtistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Artist
     * @param {Number} id 
     * @param {module:model/ArtistUpdateRequest} artistUpdateRequest 
     * @param {module:api/V1Api~updateArtistApiV1ArtistIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArtistResponse}
     */
    updateArtistApiV1ArtistIdPatch(id, artistUpdateRequest, callback) {
      let postBody = artistUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateArtistApiV1ArtistIdPatch");
      }
      // verify the required parameter 'artistUpdateRequest' is set
      if (artistUpdateRequest === undefined || artistUpdateRequest === null) {
        throw new Error("Missing the required parameter 'artistUpdateRequest' when calling updateArtistApiV1ArtistIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ArtistResponse;
      return this.apiClient.callApi(
        '/api/v1/artist/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateGenreApiV1GenrePatch operation.
     * @callback module:api/V1Api~updateGenreApiV1GenrePatchCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Genre
     * @param {module:model/GenreUpdateRequest} genreUpdateRequest 
     * @param {module:api/V1Api~updateGenreApiV1GenrePatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    updateGenreApiV1GenrePatch(genreUpdateRequest, callback) {
      let postBody = genreUpdateRequest;
      // verify the required parameter 'genreUpdateRequest' is set
      if (genreUpdateRequest === undefined || genreUpdateRequest === null) {
        throw new Error("Missing the required parameter 'genreUpdateRequest' when calling updateGenreApiV1GenrePatch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/v1/genre', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePlaylistApiV1PlaylistIdPatch operation.
     * @callback module:api/V1Api~updatePlaylistApiV1PlaylistIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Playlist
     * @param {Number} id 
     * @param {module:model/PlaylistUpdateRequest} playlistUpdateRequest 
     * @param {module:api/V1Api~updatePlaylistApiV1PlaylistIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistResponse}
     */
    updatePlaylistApiV1PlaylistIdPatch(id, playlistUpdateRequest, callback) {
      let postBody = playlistUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updatePlaylistApiV1PlaylistIdPatch");
      }
      // verify the required parameter 'playlistUpdateRequest' is set
      if (playlistUpdateRequest === undefined || playlistUpdateRequest === null) {
        throw new Error("Missing the required parameter 'playlistUpdateRequest' when calling updatePlaylistApiV1PlaylistIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlaylistResponse;
      return this.apiClient.callApi(
        '/api/v1/playlist/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSongApiV1SongIdPatch operation.
     * @callback module:api/V1Api~updateSongApiV1SongIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SongResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Song
     * @param {Number} id 
     * @param {module:model/SongUpdateRequest} songUpdateRequest 
     * @param {module:api/V1Api~updateSongApiV1SongIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongResponse}
     */
    updateSongApiV1SongIdPatch(id, songUpdateRequest, callback) {
      let postBody = songUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateSongApiV1SongIdPatch");
      }
      // verify the required parameter 'songUpdateRequest' is set
      if (songUpdateRequest === undefined || songUpdateRequest === null) {
        throw new Error("Missing the required parameter 'songUpdateRequest' when calling updateSongApiV1SongIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SongResponse;
      return this.apiClient.callApi(
        '/api/v1/song/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the uploadSongApiV1SongPost operation.
     * @callback module:api/V1Api~uploadSongApiV1SongPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SongResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload Song
     * @param {String} file 
     * @param {module:api/V1Api~uploadSongApiV1SongPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongResponse}
     */
    uploadSongApiV1SongPost(file, callback) {
      let postBody = null;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling uploadSongApiV1SongPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = SongResponse;
      return this.apiClient.callApi(
        '/api/v1/song', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
