/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PlaylistResponse {
    'id': number;
    'name': string;
    'image'?: number | null;
    'lastUpdated': Date;
    'streamCount': number;
    'lastStreamed'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "streamCount",
            "baseName": "streamCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastStreamed",
            "baseName": "lastStreamed",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PlaylistResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
