/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PlaylistCreateRequest {
    'name': string;
    'image'?: number | null;
    'songs'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "number",
            "format": ""
        },
        {
            "name": "songs",
            "baseName": "songs",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlaylistCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
