/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SongUpdateRequest {
    'genre'?: string | null;
    'artist'?: number | null;
    'album'?: number | null;
    'cover'?: number | null;
    'title'?: string | null;
    'release'?: number | null;
    'trackno'?: number | null;
    'metatags'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "genre",
            "baseName": "genre",
            "type": "string",
            "format": ""
        },
        {
            "name": "artist",
            "baseName": "artist",
            "type": "number",
            "format": ""
        },
        {
            "name": "album",
            "baseName": "album",
            "type": "number",
            "format": ""
        },
        {
            "name": "cover",
            "baseName": "cover",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "release",
            "baseName": "release",
            "type": "number",
            "format": ""
        },
        {
            "name": "trackno",
            "baseName": "trackno",
            "type": "number",
            "format": ""
        },
        {
            "name": "metatags",
            "baseName": "metatags",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SongUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
