/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SongResponse {
    'id': number;
    'title': string;
    'release'?: number | null;
    'trackno'?: number | null;
    'metatags': { [key: string]: any; };
    'lastUpdated': Date;
    'genre'?: string | null;
    'artist'?: number | null;
    'album'?: number | null;
    'cover'?: number | null;
    'streamCount': number;
    'lastStreamed'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "release",
            "baseName": "release",
            "type": "number",
            "format": ""
        },
        {
            "name": "trackno",
            "baseName": "trackno",
            "type": "number",
            "format": ""
        },
        {
            "name": "metatags",
            "baseName": "metatags",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "string",
            "format": ""
        },
        {
            "name": "artist",
            "baseName": "artist",
            "type": "number",
            "format": ""
        },
        {
            "name": "album",
            "baseName": "album",
            "type": "number",
            "format": ""
        },
        {
            "name": "cover",
            "baseName": "cover",
            "type": "number",
            "format": ""
        },
        {
            "name": "streamCount",
            "baseName": "streamCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastStreamed",
            "baseName": "lastStreamed",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SongResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
