/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumResponse
 */
export interface AlbumResponse {
    /**
     * 
     * @type {number}
     * @memberof AlbumResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AlbumResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AlbumResponse
     */
    image?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AlbumResponse
     */
    lastUpdated: Date;
    /**
     * 
     * @type {number}
     * @memberof AlbumResponse
     */
    artist: number;
    /**
     * 
     * @type {number}
     * @memberof AlbumResponse
     */
    streamCount: number;
    /**
     * 
     * @type {Date}
     * @memberof AlbumResponse
     */
    lastStreamed?: Date | null;
}

/**
 * Check if a given object implements the AlbumResponse interface.
 */
export function instanceOfAlbumResponse(value: object): value is AlbumResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('artist' in value) || value['artist'] === undefined) return false;
    if (!('streamCount' in value) || value['streamCount'] === undefined) return false;
    return true;
}

export function AlbumResponseFromJSON(json: any): AlbumResponse {
    return AlbumResponseFromJSONTyped(json, false);
}

export function AlbumResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'lastUpdated': (new Date(json['lastUpdated'])),
        'artist': json['artist'],
        'streamCount': json['streamCount'],
        'lastStreamed': json['lastStreamed'] == null ? undefined : (new Date(json['lastStreamed'])),
    };
}

export function AlbumResponseToJSON(json: any): AlbumResponse {
    return AlbumResponseToJSONTyped(json, false);
}

export function AlbumResponseToJSONTyped(value?: AlbumResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'lastUpdated': value['lastUpdated'].toISOString(),
        'artist': value['artist'],
        'streamCount': value['streamCount'],
        'lastStreamed': value['lastStreamed'] == null ? value['lastStreamed'] : value['lastStreamed'].toISOString(),
    };
}

