/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumUpdateRequest
 */
export interface AlbumUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof AlbumUpdateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AlbumUpdateRequest
     */
    image?: number | null;
}

/**
 * Check if a given object implements the AlbumUpdateRequest interface.
 */
export function instanceOfAlbumUpdateRequest(value: object): value is AlbumUpdateRequest {
    return true;
}

export function AlbumUpdateRequestFromJSON(json: any): AlbumUpdateRequest {
    return AlbumUpdateRequestFromJSONTyped(json, false);
}

export function AlbumUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function AlbumUpdateRequestToJSON(json: any): AlbumUpdateRequest {
    return AlbumUpdateRequestToJSONTyped(json, false);
}

export function AlbumUpdateRequestToJSONTyped(value?: AlbumUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
    };
}

