/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumCreateRequest
 */
export interface AlbumCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof AlbumCreateRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AlbumCreateRequest
     */
    image?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AlbumCreateRequest
     */
    artist: number;
}

/**
 * Check if a given object implements the AlbumCreateRequest interface.
 */
export function instanceOfAlbumCreateRequest(value: object): value is AlbumCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artist' in value) || value['artist'] === undefined) return false;
    return true;
}

export function AlbumCreateRequestFromJSON(json: any): AlbumCreateRequest {
    return AlbumCreateRequestFromJSONTyped(json, false);
}

export function AlbumCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'artist': json['artist'],
    };
}

export function AlbumCreateRequestToJSON(json: any): AlbumCreateRequest {
    return AlbumCreateRequestToJSONTyped(json, false);
}

export function AlbumCreateRequestToJSONTyped(value?: AlbumCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
        'artist': value['artist'],
    };
}

