/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistCreateRequest
 */
export interface ArtistCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ArtistCreateRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ArtistCreateRequest
     */
    image?: number | null;
}

/**
 * Check if a given object implements the ArtistCreateRequest interface.
 */
export function instanceOfArtistCreateRequest(value: object): value is ArtistCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ArtistCreateRequestFromJSON(json: any): ArtistCreateRequest {
    return ArtistCreateRequestFromJSONTyped(json, false);
}

export function ArtistCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ArtistCreateRequestToJSON(json: any): ArtistCreateRequest {
    return ArtistCreateRequestToJSONTyped(json, false);
}

export function ArtistCreateRequestToJSONTyped(value?: ArtistCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
    };
}

