/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistUpdateRequest
 */
export interface ArtistUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ArtistUpdateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ArtistUpdateRequest
     */
    image?: number | null;
}

/**
 * Check if a given object implements the ArtistUpdateRequest interface.
 */
export function instanceOfArtistUpdateRequest(value: object): value is ArtistUpdateRequest {
    return true;
}

export function ArtistUpdateRequestFromJSON(json: any): ArtistUpdateRequest {
    return ArtistUpdateRequestFromJSONTyped(json, false);
}

export function ArtistUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ArtistUpdateRequestToJSON(json: any): ArtistUpdateRequest {
    return ArtistUpdateRequestToJSONTyped(json, false);
}

export function ArtistUpdateRequestToJSONTyped(value?: ArtistUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
    };
}

