/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreResponse
 */
export interface GenreResponse {
    /**
     * 
     * @type {number}
     * @memberof GenreResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GenreResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof GenreResponse
     */
    lastUpdated: Date;
    /**
     * 
     * @type {number}
     * @memberof GenreResponse
     */
    streamCount: number;
    /**
     * 
     * @type {Date}
     * @memberof GenreResponse
     */
    lastStreamed?: Date | null;
}

/**
 * Check if a given object implements the GenreResponse interface.
 */
export function instanceOfGenreResponse(value: object): value is GenreResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('streamCount' in value) || value['streamCount'] === undefined) return false;
    return true;
}

export function GenreResponseFromJSON(json: any): GenreResponse {
    return GenreResponseFromJSONTyped(json, false);
}

export function GenreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'lastUpdated': (new Date(json['lastUpdated'])),
        'streamCount': json['streamCount'],
        'lastStreamed': json['lastStreamed'] == null ? undefined : (new Date(json['lastStreamed'])),
    };
}

export function GenreResponseToJSON(json: any): GenreResponse {
    return GenreResponseToJSONTyped(json, false);
}

export function GenreResponseToJSONTyped(value?: GenreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'lastUpdated': value['lastUpdated'].toISOString(),
        'streamCount': value['streamCount'],
        'lastStreamed': value['lastStreamed'] == null ? value['lastStreamed'] : value['lastStreamed'].toISOString(),
    };
}

