/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreCreateRequest
 */
export interface GenreCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof GenreCreateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the GenreCreateRequest interface.
 */
export function instanceOfGenreCreateRequest(value: object): value is GenreCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GenreCreateRequestFromJSON(json: any): GenreCreateRequest {
    return GenreCreateRequestFromJSONTyped(json, false);
}

export function GenreCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GenreCreateRequestToJSON(json: any): GenreCreateRequest {
    return GenreCreateRequestToJSONTyped(json, false);
}

export function GenreCreateRequestToJSONTyped(value?: GenreCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

