/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreUpdateRequest
 */
export interface GenreUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof GenreUpdateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the GenreUpdateRequest interface.
 */
export function instanceOfGenreUpdateRequest(value: object): value is GenreUpdateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GenreUpdateRequestFromJSON(json: any): GenreUpdateRequest {
    return GenreUpdateRequestFromJSONTyped(json, false);
}

export function GenreUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GenreUpdateRequestToJSON(json: any): GenreUpdateRequest {
    return GenreUpdateRequestToJSONTyped(json, false);
}

export function GenreUpdateRequestToJSONTyped(value?: GenreUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

