/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaylistCreateRequest
 */
export interface PlaylistCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaylistCreateRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PlaylistCreateRequest
     */
    image?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PlaylistCreateRequest
     */
    songs?: Array<number>;
}

/**
 * Check if a given object implements the PlaylistCreateRequest interface.
 */
export function instanceOfPlaylistCreateRequest(value: object): value is PlaylistCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PlaylistCreateRequestFromJSON(json: any): PlaylistCreateRequest {
    return PlaylistCreateRequestFromJSONTyped(json, false);
}

export function PlaylistCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'songs': json['songs'] == null ? undefined : json['songs'],
    };
}

export function PlaylistCreateRequestToJSON(json: any): PlaylistCreateRequest {
    return PlaylistCreateRequestToJSONTyped(json, false);
}

export function PlaylistCreateRequestToJSONTyped(value?: PlaylistCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
        'songs': value['songs'],
    };
}

