/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SongResponse
 */
export interface SongResponse {
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SongResponse
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    release?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    trackno?: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SongResponse
     */
    metatags: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof SongResponse
     */
    lastUpdated: Date;
    /**
     * 
     * @type {string}
     * @memberof SongResponse
     */
    genre?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    artist?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    album?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    cover?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongResponse
     */
    streamCount: number;
    /**
     * 
     * @type {Date}
     * @memberof SongResponse
     */
    lastStreamed?: Date | null;
}

/**
 * Check if a given object implements the SongResponse interface.
 */
export function instanceOfSongResponse(value: object): value is SongResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('metatags' in value) || value['metatags'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('streamCount' in value) || value['streamCount'] === undefined) return false;
    return true;
}

export function SongResponseFromJSON(json: any): SongResponse {
    return SongResponseFromJSONTyped(json, false);
}

export function SongResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SongResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'release': json['release'] == null ? undefined : json['release'],
        'trackno': json['trackno'] == null ? undefined : json['trackno'],
        'metatags': json['metatags'],
        'lastUpdated': (new Date(json['lastUpdated'])),
        'genre': json['genre'] == null ? undefined : json['genre'],
        'artist': json['artist'] == null ? undefined : json['artist'],
        'album': json['album'] == null ? undefined : json['album'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'streamCount': json['streamCount'],
        'lastStreamed': json['lastStreamed'] == null ? undefined : (new Date(json['lastStreamed'])),
    };
}

export function SongResponseToJSON(json: any): SongResponse {
    return SongResponseToJSONTyped(json, false);
}

export function SongResponseToJSONTyped(value?: SongResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'release': value['release'],
        'trackno': value['trackno'],
        'metatags': value['metatags'],
        'lastUpdated': value['lastUpdated'].toISOString(),
        'genre': value['genre'],
        'artist': value['artist'],
        'album': value['album'],
        'cover': value['cover'],
        'streamCount': value['streamCount'],
        'lastStreamed': value['lastStreamed'] == null ? value['lastStreamed'] : value['lastStreamed'].toISOString(),
    };
}

