/* tslint:disable */
/* eslint-disable */
/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SongUpdateRequest
 */
export interface SongUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof SongUpdateRequest
     */
    genre?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SongUpdateRequest
     */
    artist?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongUpdateRequest
     */
    album?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongUpdateRequest
     */
    cover?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SongUpdateRequest
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SongUpdateRequest
     */
    release?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SongUpdateRequest
     */
    trackno?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SongUpdateRequest
     */
    metatags?: string | null;
}

/**
 * Check if a given object implements the SongUpdateRequest interface.
 */
export function instanceOfSongUpdateRequest(value: object): value is SongUpdateRequest {
    return true;
}

export function SongUpdateRequestFromJSON(json: any): SongUpdateRequest {
    return SongUpdateRequestFromJSONTyped(json, false);
}

export function SongUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SongUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'genre': json['genre'] == null ? undefined : json['genre'],
        'artist': json['artist'] == null ? undefined : json['artist'],
        'album': json['album'] == null ? undefined : json['album'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'title': json['title'] == null ? undefined : json['title'],
        'release': json['release'] == null ? undefined : json['release'],
        'trackno': json['trackno'] == null ? undefined : json['trackno'],
        'metatags': json['metatags'] == null ? undefined : json['metatags'],
    };
}

export function SongUpdateRequestToJSON(json: any): SongUpdateRequest {
    return SongUpdateRequestToJSONTyped(json, false);
}

export function SongUpdateRequestToJSONTyped(value?: SongUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'genre': value['genre'],
        'artist': value['artist'],
        'album': value['album'],
        'cover': value['cover'],
        'title': value['title'],
        'release': value['release'],
        'trackno': value['trackno'],
        'metatags': value['metatags'],
    };
}

