/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlbumCreateRequest model module.
 * @module model/AlbumCreateRequest
 * @version 0.1.0
 */
class AlbumCreateRequest {
    /**
     * Constructs a new <code>AlbumCreateRequest</code>.
     * @alias module:model/AlbumCreateRequest
     * @param name {String} 
     * @param artist {Number} 
     */
    constructor(name, artist) { 
        
        AlbumCreateRequest.initialize(this, name, artist);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, artist) { 
        obj['name'] = name;
        obj['artist'] = artist;
    }

    /**
     * Constructs a <code>AlbumCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlbumCreateRequest} obj Optional instance to populate.
     * @return {module:model/AlbumCreateRequest} The populated <code>AlbumCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlbumCreateRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'Number');
            }
            if (data.hasOwnProperty('artist')) {
                obj['artist'] = ApiClient.convertToType(data['artist'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlbumCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlbumCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AlbumCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

AlbumCreateRequest.RequiredProperties = ["name", "artist"];

/**
 * @member {String} name
 */
AlbumCreateRequest.prototype['name'] = undefined;

/**
 * @member {Number} image
 */
AlbumCreateRequest.prototype['image'] = undefined;

/**
 * @member {Number} artist
 */
AlbumCreateRequest.prototype['artist'] = undefined;






export default AlbumCreateRequest;

