/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenreUpdateRequest model module.
 * @module model/GenreUpdateRequest
 * @version 0.1.0
 */
class GenreUpdateRequest {
    /**
     * Constructs a new <code>GenreUpdateRequest</code>.
     * @alias module:model/GenreUpdateRequest
     * @param oldname {String} 
     * @param newname {String} 
     */
    constructor(oldname, newname) { 
        
        GenreUpdateRequest.initialize(this, oldname, newname);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, oldname, newname) { 
        obj['oldname'] = oldname;
        obj['newname'] = newname;
    }

    /**
     * Constructs a <code>GenreUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenreUpdateRequest} obj Optional instance to populate.
     * @return {module:model/GenreUpdateRequest} The populated <code>GenreUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenreUpdateRequest();

            if (data.hasOwnProperty('oldname')) {
                obj['oldname'] = ApiClient.convertToType(data['oldname'], 'String');
            }
            if (data.hasOwnProperty('newname')) {
                obj['newname'] = ApiClient.convertToType(data['newname'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GenreUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GenreUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GenreUpdateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['oldname'] && !(typeof data['oldname'] === 'string' || data['oldname'] instanceof String)) {
            throw new Error("Expected the field `oldname` to be a primitive type in the JSON string but got " + data['oldname']);
        }
        // ensure the json data is a string
        if (data['newname'] && !(typeof data['newname'] === 'string' || data['newname'] instanceof String)) {
            throw new Error("Expected the field `newname` to be a primitive type in the JSON string but got " + data['newname']);
        }

        return true;
    }


}

GenreUpdateRequest.RequiredProperties = ["oldname", "newname"];

/**
 * @member {String} oldname
 */
GenreUpdateRequest.prototype['oldname'] = undefined;

/**
 * @member {String} newname
 */
GenreUpdateRequest.prototype['newname'] = undefined;






export default GenreUpdateRequest;

