/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlaylistResponse model module.
 * @module model/PlaylistResponse
 * @version 0.1.0
 */
class PlaylistResponse {
    /**
     * Constructs a new <code>PlaylistResponse</code>.
     * @alias module:model/PlaylistResponse
     * @param id {Number} 
     * @param name {String} 
     * @param lastUpdated {Date} 
     */
    constructor(id, name, lastUpdated) { 
        
        PlaylistResponse.initialize(this, id, name, lastUpdated);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, lastUpdated) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['last_updated'] = lastUpdated;
    }

    /**
     * Constructs a <code>PlaylistResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlaylistResponse} obj Optional instance to populate.
     * @return {module:model/PlaylistResponse} The populated <code>PlaylistResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'Number');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlaylistResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlaylistResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlaylistResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

PlaylistResponse.RequiredProperties = ["id", "name", "last_updated"];

/**
 * @member {Number} id
 */
PlaylistResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PlaylistResponse.prototype['name'] = undefined;

/**
 * @member {Number} image
 */
PlaylistResponse.prototype['image'] = undefined;

/**
 * @member {Date} last_updated
 */
PlaylistResponse.prototype['last_updated'] = undefined;






export default PlaylistResponse;

