/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SongResponse model module.
 * @module model/SongResponse
 * @version 0.1.0
 */
class SongResponse {
    /**
     * Constructs a new <code>SongResponse</code>.
     * @alias module:model/SongResponse
     * @param id {Number} 
     * @param title {String} 
     * @param metatags {Object.<String, Object>} 
     * @param lastUpdated {Date} 
     */
    constructor(id, title, metatags, lastUpdated) { 
        
        SongResponse.initialize(this, id, title, metatags, lastUpdated);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, metatags, lastUpdated) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['metatags'] = metatags;
        obj['last_updated'] = lastUpdated;
    }

    /**
     * Constructs a <code>SongResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SongResponse} obj Optional instance to populate.
     * @return {module:model/SongResponse} The populated <code>SongResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SongResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('release')) {
                obj['release'] = ApiClient.convertToType(data['release'], 'Number');
            }
            if (data.hasOwnProperty('trackno')) {
                obj['trackno'] = ApiClient.convertToType(data['trackno'], 'Number');
            }
            if (data.hasOwnProperty('metatags')) {
                obj['metatags'] = ApiClient.convertToType(data['metatags'], {'String': Object});
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], 'String');
            }
            if (data.hasOwnProperty('artist')) {
                obj['artist'] = ApiClient.convertToType(data['artist'], 'Number');
            }
            if (data.hasOwnProperty('album')) {
                obj['album'] = ApiClient.convertToType(data['album'], 'Number');
            }
            if (data.hasOwnProperty('cover')) {
                obj['cover'] = ApiClient.convertToType(data['cover'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SongResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SongResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SongResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['genre'] && !(typeof data['genre'] === 'string' || data['genre'] instanceof String)) {
            throw new Error("Expected the field `genre` to be a primitive type in the JSON string but got " + data['genre']);
        }

        return true;
    }


}

SongResponse.RequiredProperties = ["id", "title", "metatags", "last_updated"];

/**
 * @member {Number} id
 */
SongResponse.prototype['id'] = undefined;

/**
 * @member {String} title
 */
SongResponse.prototype['title'] = undefined;

/**
 * @member {Number} release
 */
SongResponse.prototype['release'] = undefined;

/**
 * @member {Number} trackno
 */
SongResponse.prototype['trackno'] = undefined;

/**
 * @member {Object.<String, Object>} metatags
 */
SongResponse.prototype['metatags'] = undefined;

/**
 * @member {Date} last_updated
 */
SongResponse.prototype['last_updated'] = undefined;

/**
 * @member {String} genre
 */
SongResponse.prototype['genre'] = undefined;

/**
 * @member {Number} artist
 */
SongResponse.prototype['artist'] = undefined;

/**
 * @member {Number} album
 */
SongResponse.prototype['album'] = undefined;

/**
 * @member {Number} cover
 */
SongResponse.prototype['cover'] = undefined;






export default SongResponse;

