/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SongUpdateRequest model module.
 * @module model/SongUpdateRequest
 * @version 0.1.0
 */
class SongUpdateRequest {
    /**
     * Constructs a new <code>SongUpdateRequest</code>.
     * @alias module:model/SongUpdateRequest
     */
    constructor() { 
        
        SongUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SongUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SongUpdateRequest} obj Optional instance to populate.
     * @return {module:model/SongUpdateRequest} The populated <code>SongUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SongUpdateRequest();

            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], 'String');
            }
            if (data.hasOwnProperty('artist')) {
                obj['artist'] = ApiClient.convertToType(data['artist'], 'Number');
            }
            if (data.hasOwnProperty('album')) {
                obj['album'] = ApiClient.convertToType(data['album'], 'Number');
            }
            if (data.hasOwnProperty('cover')) {
                obj['cover'] = ApiClient.convertToType(data['cover'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('release')) {
                obj['release'] = ApiClient.convertToType(data['release'], 'Number');
            }
            if (data.hasOwnProperty('trackno')) {
                obj['trackno'] = ApiClient.convertToType(data['trackno'], 'Number');
            }
            if (data.hasOwnProperty('metatags')) {
                obj['metatags'] = ApiClient.convertToType(data['metatags'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SongUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SongUpdateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['genre'] && !(typeof data['genre'] === 'string' || data['genre'] instanceof String)) {
            throw new Error("Expected the field `genre` to be a primitive type in the JSON string but got " + data['genre']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['metatags'] && !(typeof data['metatags'] === 'string' || data['metatags'] instanceof String)) {
            throw new Error("Expected the field `metatags` to be a primitive type in the JSON string but got " + data['metatags']);
        }

        return true;
    }


}



/**
 * @member {String} genre
 */
SongUpdateRequest.prototype['genre'] = undefined;

/**
 * @member {Number} artist
 */
SongUpdateRequest.prototype['artist'] = undefined;

/**
 * @member {Number} album
 */
SongUpdateRequest.prototype['album'] = undefined;

/**
 * @member {Number} cover
 */
SongUpdateRequest.prototype['cover'] = undefined;

/**
 * @member {String} title
 */
SongUpdateRequest.prototype['title'] = undefined;

/**
 * @member {Number} release
 */
SongUpdateRequest.prototype['release'] = undefined;

/**
 * @member {Number} trackno
 */
SongUpdateRequest.prototype['trackno'] = undefined;

/**
 * @member {String} metatags
 */
SongUpdateRequest.prototype['metatags'] = undefined;






export default SongUpdateRequest;

