/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AudioServer);
  }
}(this, function(expect, AudioServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AudioServer.AlbumApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlbumApi', function() {
    describe('createAlbumApiV1AlbumPost', function() {
      it('should call createAlbumApiV1AlbumPost successfully', function(done) {
        //uncomment below and update the code to test createAlbumApiV1AlbumPost
        //instance.createAlbumApiV1AlbumPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAlbumApiV1AlbumIdDelete', function() {
      it('should call deleteAlbumApiV1AlbumIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteAlbumApiV1AlbumIdDelete
        //instance.deleteAlbumApiV1AlbumIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAlbumApiV1AlbumIdGet', function() {
      it('should call getAlbumApiV1AlbumIdGet successfully', function(done) {
        //uncomment below and update the code to test getAlbumApiV1AlbumIdGet
        //instance.getAlbumApiV1AlbumIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet', function() {
      it('should call getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet successfully', function(done) {
        //uncomment below and update the code to test getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet
        //instance.getAlbumsFromPlaylistApiV1PlaylistIdAlbumsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFeaturesFromAlbumApiV1AlbumIdFeaturesGet', function() {
      it('should call getFeaturesFromAlbumApiV1AlbumIdFeaturesGet successfully', function(done) {
        //uncomment below and update the code to test getFeaturesFromAlbumApiV1AlbumIdFeaturesGet
        //instance.getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenresFromAlbumApiV1AlbumIdGenresGet', function() {
      it('should call getGenresFromAlbumApiV1AlbumIdGenresGet successfully', function(done) {
        //uncomment below and update the code to test getGenresFromAlbumApiV1AlbumIdGenresGet
        //instance.getGenresFromAlbumApiV1AlbumIdGenresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromAlbumApiV1AlbumIdSongsGet', function() {
      it('should call getSongsFromAlbumApiV1AlbumIdSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromAlbumApiV1AlbumIdSongsGet
        //instance.getSongsFromAlbumApiV1AlbumIdSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllAlbumsApiV1AlbumsGet', function() {
      it('should call listAllAlbumsApiV1AlbumsGet successfully', function(done) {
        //uncomment below and update the code to test listAllAlbumsApiV1AlbumsGet
        //instance.listAllAlbumsApiV1AlbumsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAlbumApiV1AlbumIdPatch', function() {
      it('should call updateAlbumApiV1AlbumIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateAlbumApiV1AlbumIdPatch
        //instance.updateAlbumApiV1AlbumIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
