/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AudioServer);
  }
}(this, function(expect, AudioServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AudioServer.ArtistApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArtistApi', function() {
    describe('createArtistApiV1ArtistPost', function() {
      it('should call createArtistApiV1ArtistPost successfully', function(done) {
        //uncomment below and update the code to test createArtistApiV1ArtistPost
        //instance.createArtistApiV1ArtistPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteArtistApiV1ArtistIdDelete', function() {
      it('should call deleteArtistApiV1ArtistIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteArtistApiV1ArtistIdDelete
        //instance.deleteArtistApiV1ArtistIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArtistApiV1ArtistIdGet', function() {
      it('should call getArtistApiV1ArtistIdGet successfully', function(done) {
        //uncomment below and update the code to test getArtistApiV1ArtistIdGet
        //instance.getArtistApiV1ArtistIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArtistsFromPlaylistApiV1PlaylistIdArtistsGet', function() {
      it('should call getArtistsFromPlaylistApiV1PlaylistIdArtistsGet successfully', function(done) {
        //uncomment below and update the code to test getArtistsFromPlaylistApiV1PlaylistIdArtistsGet
        //instance.getArtistsFromPlaylistApiV1PlaylistIdArtistsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet', function() {
      it('should call getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet successfully', function(done) {
        //uncomment below and update the code to test getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet
        //instance.getCollaborationsFromArtistApiV1ArtistIdCollaborationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFeaturesFromAlbumApiV1AlbumIdFeaturesGet', function() {
      it('should call getFeaturesFromAlbumApiV1AlbumIdFeaturesGet successfully', function(done) {
        //uncomment below and update the code to test getFeaturesFromAlbumApiV1AlbumIdFeaturesGet
        //instance.getFeaturesFromAlbumApiV1AlbumIdFeaturesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFeaturesFromArtistApiV1ArtistIdFeaturesGet', function() {
      it('should call getFeaturesFromArtistApiV1ArtistIdFeaturesGet successfully', function(done) {
        //uncomment below and update the code to test getFeaturesFromArtistApiV1ArtistIdFeaturesGet
        //instance.getFeaturesFromArtistApiV1ArtistIdFeaturesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFeaturesFromSongApiV1SongIdFeaturesGet', function() {
      it('should call getFeaturesFromSongApiV1SongIdFeaturesGet successfully', function(done) {
        //uncomment below and update the code to test getFeaturesFromSongApiV1SongIdFeaturesGet
        //instance.getFeaturesFromSongApiV1SongIdFeaturesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenresFromArtistApiV1ArtistIdGenresGet', function() {
      it('should call getGenresFromArtistApiV1ArtistIdGenresGet successfully', function(done) {
        //uncomment below and update the code to test getGenresFromArtistApiV1ArtistIdGenresGet
        //instance.getGenresFromArtistApiV1ArtistIdGenresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromArtistApiV1ArtistIdSongsGet', function() {
      it('should call getSongsFromArtistApiV1ArtistIdSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromArtistApiV1ArtistIdSongsGet
        //instance.getSongsFromArtistApiV1ArtistIdSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllArtistApiV1ArtistsGet', function() {
      it('should call listAllArtistApiV1ArtistsGet successfully', function(done) {
        //uncomment below and update the code to test listAllArtistApiV1ArtistsGet
        //instance.listAllArtistApiV1ArtistsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateArtistApiV1ArtistIdPatch', function() {
      it('should call updateArtistApiV1ArtistIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateArtistApiV1ArtistIdPatch
        //instance.updateArtistApiV1ArtistIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
