/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AudioServer);
  }
}(this, function(expect, AudioServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AudioServer.GenreApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GenreApi', function() {
    describe('createGenreApiV1GenrePost', function() {
      it('should call createGenreApiV1GenrePost successfully', function(done) {
        //uncomment below and update the code to test createGenreApiV1GenrePost
        //instance.createGenreApiV1GenrePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGenreApiV1GenreDelete', function() {
      it('should call deleteGenreApiV1GenreDelete successfully', function(done) {
        //uncomment below and update the code to test deleteGenreApiV1GenreDelete
        //instance.deleteGenreApiV1GenreDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenresFromAlbumApiV1AlbumIdGenresGet', function() {
      it('should call getGenresFromAlbumApiV1AlbumIdGenresGet successfully', function(done) {
        //uncomment below and update the code to test getGenresFromAlbumApiV1AlbumIdGenresGet
        //instance.getGenresFromAlbumApiV1AlbumIdGenresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenresFromArtistApiV1ArtistIdGenresGet', function() {
      it('should call getGenresFromArtistApiV1ArtistIdGenresGet successfully', function(done) {
        //uncomment below and update the code to test getGenresFromArtistApiV1ArtistIdGenresGet
        //instance.getGenresFromArtistApiV1ArtistIdGenresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenresFromPlaylistApiV1PlaylistIdGenresGet', function() {
      it('should call getGenresFromPlaylistApiV1PlaylistIdGenresGet successfully', function(done) {
        //uncomment below and update the code to test getGenresFromPlaylistApiV1PlaylistIdGenresGet
        //instance.getGenresFromPlaylistApiV1PlaylistIdGenresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromGenreApiV1GenreSongsGet', function() {
      it('should call getSongsFromGenreApiV1GenreSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromGenreApiV1GenreSongsGet
        //instance.getSongsFromGenreApiV1GenreSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllGenresApiV1GenresGet', function() {
      it('should call listAllGenresApiV1GenresGet successfully', function(done) {
        //uncomment below and update the code to test listAllGenresApiV1GenresGet
        //instance.listAllGenresApiV1GenresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGenreApiV1GenrePatch', function() {
      it('should call updateGenreApiV1GenrePatch successfully', function(done) {
        //uncomment below and update the code to test updateGenreApiV1GenrePatch
        //instance.updateGenreApiV1GenrePatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
