/**
 * Audio Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AudioServer);
  }
}(this, function(expect, AudioServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AudioServer.SongApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SongApi', function() {
    describe('deleteSongApiV1SongIdDelete', function() {
      it('should call deleteSongApiV1SongIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteSongApiV1SongIdDelete
        //instance.deleteSongApiV1SongIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFeaturesFromArtistApiV1ArtistIdFeaturesGet', function() {
      it('should call getFeaturesFromArtistApiV1ArtistIdFeaturesGet successfully', function(done) {
        //uncomment below and update the code to test getFeaturesFromArtistApiV1ArtistIdFeaturesGet
        //instance.getFeaturesFromArtistApiV1ArtistIdFeaturesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFeaturesFromSongApiV1SongIdFeaturesGet', function() {
      it('should call getFeaturesFromSongApiV1SongIdFeaturesGet successfully', function(done) {
        //uncomment below and update the code to test getFeaturesFromSongApiV1SongIdFeaturesGet
        //instance.getFeaturesFromSongApiV1SongIdFeaturesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet', function() {
      it('should call getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet successfully', function(done) {
        //uncomment below and update the code to test getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet
        //instance.getPlaylistsSongIsPartOfApiV1SongIdPlaylistsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongApiV1SongIdGet', function() {
      it('should call getSongApiV1SongIdGet successfully', function(done) {
        //uncomment below and update the code to test getSongApiV1SongIdGet
        //instance.getSongApiV1SongIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromAlbumApiV1AlbumIdSongsGet', function() {
      it('should call getSongsFromAlbumApiV1AlbumIdSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromAlbumApiV1AlbumIdSongsGet
        //instance.getSongsFromAlbumApiV1AlbumIdSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromArtistApiV1ArtistIdSongsGet', function() {
      it('should call getSongsFromArtistApiV1ArtistIdSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromArtistApiV1ArtistIdSongsGet
        //instance.getSongsFromArtistApiV1ArtistIdSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromGenreApiV1GenreSongsGet', function() {
      it('should call getSongsFromGenreApiV1GenreSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromGenreApiV1GenreSongsGet
        //instance.getSongsFromGenreApiV1GenreSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSongsFromPlaylistApiV1PlaylistIdSongsGet', function() {
      it('should call getSongsFromPlaylistApiV1PlaylistIdSongsGet successfully', function(done) {
        //uncomment below and update the code to test getSongsFromPlaylistApiV1PlaylistIdSongsGet
        //instance.getSongsFromPlaylistApiV1PlaylistIdSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllSongApiV1SongsGet', function() {
      it('should call listAllSongApiV1SongsGet successfully', function(done) {
        //uncomment below and update the code to test listAllSongApiV1SongsGet
        //instance.listAllSongApiV1SongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('streamSongApiV1SongIdStreamGet', function() {
      it('should call streamSongApiV1SongIdStreamGet successfully', function(done) {
        //uncomment below and update the code to test streamSongApiV1SongIdStreamGet
        //instance.streamSongApiV1SongIdStreamGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSongApiV1SongIdPatch', function() {
      it('should call updateSongApiV1SongIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateSongApiV1SongIdPatch
        //instance.updateSongApiV1SongIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadSongApiV1SongPost', function() {
      it('should call uploadSongApiV1SongPost successfully', function(done) {
        //uncomment below and update the code to test uploadSongApiV1SongPost
        //instance.uploadSongApiV1SongPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
